apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: mimir
  namespace: monitoring
spec:
  clusterRef:
    name: the-works
    namespace: object-storage
  quotas:
    maxSize: 50Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: mimir-key
  namespace: monitoring
spec:
  clusterRef:
    name: the-works
    namespace: object-storage
  bucketPermissions:
    - bucketRef:
        name: mimir
      read: true
      write: true
