apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin-credentials
    namespace: cloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:EfcIHPc=,iv:znaKtM15VrJec1/EPCUBSROqqTEKFIAbOIz+Jd2AG7c=,tag:YgY7M1ZbsMRjzLClO7C/gQ==,type:str]
    password: ENC[AES256_GCM,data:LcEOnKngSy6Xmqb7kM3i05kgbBJ9lQo8c15CB9AAo+Q3QDduugGTN/HN,iv:c6WyhvA/IYRGJgga2MU6EZl37yPSe89qHPT3pz8JpNE=,tag:Rpartxt/3mkeNp0fR0/OvA==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSlVTbEJtY2UyR2VydlJL
            Zmc4YjRJNWF0bmtoTjV1RFpFTWUxWnVzS2lZCkE3a0NVemhjb1ByUHhaaGM4RE9k
            dTN4ZkdLNS9qSExJd0t0RUZWbk5xRkUKLS0tIGFoblRKNXlSYmZiOHFsR3EzTnZX
            VnBxbEpFeXk1RnlzdWo2OVAwVXZVTWsKSCh+CWDM1xxHxGwG4os7z7I8rnV2XUYK
            N9q68OZiSUnDUatbW6Au7h4ozZHwNTHk5h2A0FK/OGYNdCXhwEwSiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneHRWOVNKUWRmUFg3aFFV
            VTk0YzJhajRVY2M5L1hueSswRTJMdnVrQ3drClVJdGRkaXJiRUpKRWxxcUhJYTBq
            Z1I5TnNCRkYrcUlRYnN3bjljaTU2ZXcKLS0tIDBOS0l4Ujl2OGljRTgvL2RoYm54
            N25lbVBudk01clZtYzhRSTc5ZkJ1d0UKCntgifMMw8sny931SdqUXvrZSsukjrab
            KLuT5hllz6UTEsfr7ia84dkUjTPfZUoqHWx9DOoYE66/ENpV4Wosbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T11:14:28Z"
    mac: ENC[AES256_GCM,data:qhWmLCSGdCyGMUT37QB/Hc6OZEjqDd5DTPGxsNG3RgeN7w4tpkZSenY/THWpOPocy86mu+fR9hus/3tC0EKhQpGfJ2Jw0W938Eb2YEi7Wkpt7oRmc7svMUfuPbKskaT0IcBYoP/3Ey5F337tD18HN5PObyNEWvFdi2raQ/l4FQU=,iv:Ssv6PavHOiO/TJ9C4YXIE2cXkkS3EAG+neJKXZHodKY=,tag:jWxzQ4d3znOClsUe/uWhaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
