apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-credentials
    namespace: cloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:sViw3LlAlEYr,iv:YlLhRF9gC4XgdrTKaCp8E3RyOSn/tE1ZddvmDoNEs98=,tag:/h73Pdx/PIknkwwOkAElEA==,type:str]
    password: ENC[AES256_GCM,data:H8f3j8DpkM97kzhSMG278bs8Ti02aRuRCyGUh6dutPuzt0IkFpjw+z3tAIP5wk/1XT3PmXtO+ZLK2QoEQ4GEhA==,iv:hy7wv1WOW9e7/102TOlnSVEWaPtAiWirf6yKD/V5jLI=,tag:eIlOzvHVg6pBojiFs8zfAg==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZVc2b2J2cko2TEswRytp
            VXdXNkhmMVpndDRWd0dRYmpZcEwxaUdaRng4CkFEY3lkYWtsU2lYTTN0aUJoWkFz
            cDhoZHJHWXJIMWZwNXptV0RKVS9QUjQKLS0tIFEzV2Nlc3RtQlN2TTdJV3hlVXJa
            eFdLdjd2cmpwZnBoNlE0ZFNWcHVKVGcKgSzH4DeTGqtrCcNoPnRIxiWT9UnMryYg
            ZK/MuIFGRRBI0aV2ii587Tx0IxaUfLFzKnyVOce4UFLeFHm0h9mafA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RDhuSERaQ1JHRTdLUkp3
            Z0xKYi94RmdZMWUvVVBqckN4TXkvOEVGNlZrCnJFRC8yK3hmMXRQVWdJSndiL0pl
            WGlFMEsvcVg2M0FDQzIzRXYzV0RIS00KLS0tIHVqazdLYUhxalB5b3NKSVBtWVBq
            SVVGaXZFRGxIY1RRYnUrUkcxTlp1bTQKWUUBerAMfyu1HNdl+sv8Lf/WRiZfNCas
            wzmPdAjBdsHxu+SSfOTFOQsKk1Z6ShDIYzMVRw10vlZs4f0PuX/eng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T11:11:57Z"
    mac: ENC[AES256_GCM,data:CeJBo6gNO/5C0J9AzYQ96Vo1Jr0LqHYdGNWiBvc5InMx7SHiUUOhbjvcS1pXlf8VWMx6fNPcrypk9n1yJQcZ1OzZq4FITNDeHXHCi8294QtftZEK05yQ6W1aHesxSwtH7lZh4qfb6zt8yd83AkoUIOiVm8YYn3AMqwjefpayQ5E=,iv:31I2FWNaT4s51XSEwO/cbP6KDthcXcfrZ7hq3HVM10g=,tag:QFdFHci+Hi1HRxL3ywkq1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
