apiVersion: v1
kind: Service
metadata:
  name: local-nextcloud
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: home.cloud.titusio.net
    external-dns.alpha.kubernetes.io/ttl: "60"
    "lbipam.cilium.io/ips": "10.0.40.109"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 443
      targetPort: 443
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nextcloud-ips
  namespace: networking
spec:
  endpoints:
    - dnsName: "cloud.titusio.net"
      recordType: A
      recordTTL: 60
      targets:
        - "204.168.137.124"
    - dnsName: "office.titusio.net"
      recordType: A
      recordTTL: 60
      targets:
        - "204.168.137.124"
