apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-redis-credentials
    namespace: cloud
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:JaAP2gW7MRNiWRfVbkneD+4YKFEhCzytvwWIY5sy10EPNXSeH4Dz1ao6+R3j/ogYr74wUkZGekr/clR2g+oe8A==,iv:etIdS2Te2dDUQCuiU9B7VMHSicMsyLcZeGhUxslWK7Y=,tag:CjqxzHOVZiz889w0IHhQlA==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEhVQzNtcjhwd0liREUz
            cEZaVVA2QnJuWDdwSEhRTmtJa2xjWmJIcG40ClV2eXZxVXdPa0VJbVE0SkR4VTRT
            aXh2aWRuMldVeXdkSzAzVUd1VTFqaWcKLS0tIHJOYkRaTFdnZHpOR3c5UEE0aDhr
            UHZ0SVdHZkQxMGQzRUQ0YzBvYTIxbDgKxru2U4OKXONCS3byDkPYehC//h7hezwZ
            aaMeVQKkdQiidXh41Z2al0ZIIPgq84FZLtRrFamxRSB3CN17tv8AUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYk5mdU5JU3JjaE1ud3RZ
            SnZ4MnVzcThtRXBqR3N5S2JXblRJditFbzNJClV0YVhrNUd4UHhvZ29pTUJkSU1P
            ZXpkU0NCWlJEekZYRmZWdnZYL05RWkUKLS0tIHh2Qk5kVW9vcGIvK1lYQ3o5RjND
            NmF4TnVRWjMwcEo3TTdSek9aa0pQT0kK1+ZwPuSiFZTPYIA3coe0zX3by1qr6XfV
            EwWYmXDh3/H/aD2gI8+/nKkm4z4oj1aco5xtlnRy34sVnt2gTKz5ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T11:24:12Z"
    mac: ENC[AES256_GCM,data:w4IfuwrUL5vJ74pqRa1WvRYm7P0hzIA3GlsuZXt8QXXh20VwaX1cLtKi9Jxmk/nLrJSt8X9peVcXeQizCRLcvZ8osga8el8pAka4YXFmCrWyURx8N5l1oVVbpjdxqvuES1UyeWXPT5SW3kYyiTSUkEkx3hdxVfkvOwhcKBq1muU=,iv:JKXU/76w4Gj5yrBIoKCPBRbAa0UNDigz2HUvypm+X6o=,tag:JOvb3XXj/h6KWIQFyKK3LQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
