apiVersion: batch/v1
kind: Job
metadata:
  name: wiredoor-register-nextcloud
  namespace: gateway
spec:
  template:
    spec:
      containers:
      - name: wiredoor-cli
        image: wiredoor/wiredoor-cli:v1.2.0
        command:
        - sh
        - -c
        - |
          wiredoor config --url=$WIREDOOR_URL --token=$WIREDOOR_TOKEN
          wiredoor http nextcloud \
            --domain cloud.titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 80 --proto http
          wiredoor http collabora \
            --domain office.titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 80 --proto http
        env:
        - name: WIREDOOR_URL
          valueFrom:
            secretKeyRef:
              name: wiredoor-config
              key: WIREDOOR_URL
        - name: WIREDOOR_TOKEN
          valueFrom:
            secretKeyRef:
              name: wiredoor-config
              key: TOKEN
      restartPolicy: OnFailure
