apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: source-control
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:y1VqjaPaaMNU5mH/fqUmjINf7Il7nQGRuN3DeKcnSdUep7eST6zNcQkpnqbXBS6+RpAqCTlh3lOdAjZh5XLypKSMzqkuEpEbw2SVxMotOSVRtzrO8MAo8Fm1oXoB37AtCrwevExbEQ0BmTa3PBbf+E3Hqi/L67q0Nw6z9ClTG/IpPTo4aKkpV0aHFThEmSy2O9TUZP0oA8LYwaa/6ZnXRwSiPYaFlrKDuXmtuz/4eu6PW3EKfeeURO1RVKW4Xg76uexy5AoK2nCfjPR3FVDPKdw0q+vjex6RwOEwGFxRWze2mzqqjw/I0r3vJAaIDciBfHXlUjwUMLVuMmnM4/81Y/DqHw==,iv:KIv/h9qyy+86wBtcEBvivsi6UWZYq1DvU4XmJIY6pjI=,tag:+tExoebfcnQx8buij3bh+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVGhRTTZYVjdGbjhhT0hs
            dkdROE1EcFE3WFVOV2tvYlFobWE1bEJGZXlBCk5kTWc2bGRrNitzKzdya0p3WDdU
            N1RBRnFLVTY2U2ZVbmtKWGwvZzcvUmMKLS0tIERjN2cvMEdNKzRhaG13TjNkWXUw
            SlBTTVRFNmNXbTRvdDJBZk1QS3ViK1kKkwXKc4uL8VbBU2EipO3WF2Twnv6enFBg
            8tLZ0sOz3tBXD3/RD60kfbLNJyY3ygsu/ywthrfIVJZPvnNBWU/NNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUTBqYnFSMlNFMThnWEdq
            UFhTaU9rWmZDMkhvSXdtcFJ2TVNCcDVXMHhNCmRxbjlGdGNIcTBKc2NCZ05PaWVx
            Y0VXZDE3SUxiaHFFVGRudGhUcnByNmcKLS0tIDVPbm92V2d6cmpkcEdLbFlyTENQ
            N1IwOFlYZUtkVGVtVlpHVlV2VVhITDgK1ykfY2+xfOO11fjPnyVsUc0PSAffJYIN
            3zUBhrPtvi2ktKBgfSe9/vVd6OugeZkRNuLdDtp5X8bbf9gcajz+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T15:41:51Z"
    mac: ENC[AES256_GCM,data:XDrBDrsPGx+3VoVfEaJTX4bZnzyxEvsWQmO1GnEimk4of7lBDXE8sKCnUcU9AKoTXnSCiRakpIh6Sh2KpS15KaYpn5MsrdJ50SwknPRARJa/Ue8iWOFrJoq+wRzYD9NzT9s3t5ulzmoszp8t2Ghy8NKC8iGKuTGrWCODVBPqjWg=,iv:uWYLYCt5fzAyj2VboSIlnNApKdXqNELo0Vw3uRkWHq8=,tag:j5Sp5n/+YyB0DtJMYy0Cgg==,type:str]
    version: 3.13.1
