apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: source-control
data:
  config.yaml: |
    container:
      network: host
      options: >-
        -v /certs:/certs
        -e DOCKER_HOST=tcp://localhost:2376
        -e DOCKER_TLS_VERIFY=1
        -e DOCKER_CERT_PATH=/certs/client
      valid_volumes:
        - /certs
    server:
      connections:
        forgejo:
          url: https://git.titusio.net/
          uuid: 79d7ef92-fd28-4444-9d82-0701fbf1e301
          token_url: file:/etc/runner-token/token
          labels:
            - "docker:docker://docker:latest"
            - "ubuntu-22.04:docker://node:16-bullseye"
