apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: source-control
type: Opaque
stringData:
    .runner: ENC[AES256_GCM,data:iDk/sMzbcGSyjeHc0VMV+04nldg+NUXhMn4OjVus7IuGOUOeVixfQ+qfOiyO2nCjt/h7k52PdQe00DZJI/kG39oUbyXa0qWqLhQXlvy+feEOCvfJA6y+HjZ9hISuMSnJQxDjFOzTdjuNQ3T9pEzzLL6BZv7LuwLZnU0nL7hI/wrG61YLBRaY0iS6Wwm7PEsHxs18W/jNO5RoLar1dlDx5T8veGYWpiTTBdlZoOHg9g==,iv:xylKsNpxWqIvwnjx4hPZh4lGwDkSD3adCDL23YwgKNA=,tag:vTWv9AqLyHiAXnlhxD4IYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ2FPNnQ1dnVOZmFFcmty
            dTNadCtPOGloZk5xeXZPaS9zWDRtZ2FkNGlFCkVKYzRwNzZnVVJEdnJ6L0t5VHl3
            SHBqWnpiY2toSlhNU2NzdnM0bUhIRUkKLS0tIGpsZmhBUVdlMFR3SEhrek1PaHZJ
            TkY1YzAzajM0L01aZmR3bDdHUS8yblkKR5B+KQ9ToDbvOo14zPowcIETjry1HgE9
            U/wHOVBpseeZZIi25AS6AFZZxPaW0VardeqieVtGERi4ZK2k6OxbKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWm1pbXczZUdXSERFV21u
            ZzJrQTVPS3dUL09ZRzVYTUcweEt1Q3ZGakF3CmdTbUZjNGxVM1F2aFlnd25Zc3dW
            d0t5Z0VBTHdrL3NPOHlqSFR0WEZMOFEKLS0tIFVKS3lHeWFMWkxiRjBhSlM4Qy96
            cUJKa0VsSUNKVit1QVpVMU5FcktNbEUK8YcChHLM5LOn5uKPQWJfKm9AigeyfNYz
            tgkFbdVWWGYQAYwSubhRw0X0ctLnFHEEI9qx2kqF3qFT+cEuPE8WSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T10:56:45Z"
    mac: ENC[AES256_GCM,data:Srlc3rDk686VXsyqdjmYR3nTXSnL+mYcqZgQ4NUZGFAQQnGlOFJJ6RPMt/NA+iZv3nrWbgzJFIuass2TgZdG6FwFqzTDFqBXxwNlkgG9OLAJU+uV7+rCRbjzJwzS70sGfE0yGZWV5T2U95DistwjXQ28Xbf0a0dJgc9xVLINFnA=,iv:WYuqpjgMrpoHJa9QiC/Xe1EsrSbyBvkIdu3SU0YqdIE=,tag:+9I+bthc1sYZKk9AtawjKg==,type:str]
    version: 3.13.1
