apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: source-control
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:TZLMQqwosJ8RwtAdSWfcWthn+5dQBTRsfaH0ecTEdgRfmxEabzl1gM+oA7cwDSKJchNKh2DfnvWRD8jyDtHGC42Hq2bpVA8SZJs7LV2iH32tUxhLe1y4tOU66uIhpg6CL5SONV8eTwc1Nz3sCo7Gg+pyZtmvG0cKQ664D0XLixWN6yYixDfw5GRnfSou5HngNkjvHMbVZadS2jEpcsCZmuB7UEb9wtcImZfn46z6ITh8/odnrRrj9e661Jy60D4S8IskCkOAKNCtp9bOkzN5sWC/jyfIoT1co/BysBl3Yw7vbKzmrlpffCi4KnclPL3u,iv:lMyfp9ffzZ7wXZ/5BGooyeE0oC9SyCYPRHQbiUzGono=,tag:/CyT8SfvoUjCnw8B+nwqyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVGhRTTZYVjdGbjhhT0hs
            dkdROE1EcFE3WFVOV2tvYlFobWE1bEJGZXlBCk5kTWc2bGRrNitzKzdya0p3WDdU
            N1RBRnFLVTY2U2ZVbmtKWGwvZzcvUmMKLS0tIERjN2cvMEdNKzRhaG13TjNkWXUw
            SlBTTVRFNmNXbTRvdDJBZk1QS3ViK1kKkwXKc4uL8VbBU2EipO3WF2Twnv6enFBg
            8tLZ0sOz3tBXD3/RD60kfbLNJyY3ygsu/ywthrfIVJZPvnNBWU/NNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUTBqYnFSMlNFMThnWEdq
            UFhTaU9rWmZDMkhvSXdtcFJ2TVNCcDVXMHhNCmRxbjlGdGNIcTBKc2NCZ05PaWVx
            Y0VXZDE3SUxiaHFFVGRudGhUcnByNmcKLS0tIDVPbm92V2d6cmpkcEdLbFlyTENQ
            N1IwOFlYZUtkVGVtVlpHVlV2VVhITDgK1ykfY2+xfOO11fjPnyVsUc0PSAffJYIN
            3zUBhrPtvi2ktKBgfSe9/vVd6OugeZkRNuLdDtp5X8bbf9gcajz+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T11:02:31Z"
    mac: ENC[AES256_GCM,data:8ah9RisfsfdtXALtIJnrGtXtB+tjn3XED1DzNeqll/pkj9/S+H6U8Hzy0Fx1my3Ld58+b0cYCMZbKWUamoNcN54EM/ubtHa+ZcCsl6AedKqFcHTrqzNXVDgie7Rf1Cgd571aLMxS9LbeLVEy3h//Ncw/nugFm0sD0718x6s/gM0=,iv:59TOVclYyvvUrsD7S6TZtHzGQHVpcXH4L13Wvg/tvNY=,tag:f3lVP3k76Jopv0JmwWZUqw==,type:str]
    version: 3.13.1
