apiVersion: v1
kind: Secret
metadata:
    name: hugo-runner-secret
    namespace: source-control
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:wkDZBIgrZ33Uddctd/Dgt9rAJgAgiCTYZKZofAyO2RiD07kIylrEaA==,iv:lBn54cIrjy5yiRLeTfEL97DDauUqoHC773f9dWMvWmY=,tag:xvWLHb1g8J45ETjnCKso5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eWZGOW9heWN3VVhLL25k
            VUhndWJRWUxGY3FwRVFZeTUxNXRxd3ZUU0hVCk1pbmVyNWM3SEFSMHZwb3pSbkFh
            Yk1OVU1JcHd5VFZnUHVKNjYwN29EeWsKLS0tIEFEdW9zQmZkUHZ5RFFtMWxiMWQ0
            UTR5cjdBZjZPVEZHK0pFSFJpbnNBeTQKRplXX6422aHnUXkOaLeGs0/57DgbjUk8
            PLUwyvphzA/3CXtN+oaMFoFTUxwsC3yterHseiALQawEUzoJCIUwCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTWN1Z2hXTXQ0MHB1L3ll
            TVE5U2JwU1ZCb05rc0Jlbkd3eitCMEdrQVY0CkhnN1QxVU84cFZnb0tpV2UwNU4z
            RGora3pmamVtMUExOE4yQ1kxbk14Z3MKLS0tIGk5VGt2S0NGYTFXSlpENCt0Q01P
            ekcyVllRREpaRmVLNjRhN1ZjTWp6aGMKqHnSrRpJn5mRgOPdK7QqeY8Kn6IoSkGl
            QJ8epl1RBIIVpnswFHUSccgUB5gjirqCu5j4MIKNCN7k+5bsXUG46g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T05:24:39Z"
    mac: ENC[AES256_GCM,data:Ov7dwVVfPbhuzNrdcP/IrZw/WOTnr3nFUKbiBFtCVWk7NhNaWnSMZp1U9ClsK+sBmt9ZDgwoFUBaK1dNeA/uYYeVY2LZcT7jvnF4x2c+swKRHZVTapMOduwX9CY0b0i5jOqn6bUlBRz08CbOsKR2BMjkcH/S8CvpnPyErFh9uRs=,iv:dzJjBJTACJUjtGX8IppaVJziGGA0l9HG6iFU6gbZAtA=,tag:cDgjxfUb6VmChfGMdy3lvw==,type:str]
    version: 3.13.1
