apiVersion: v1
kind: Secret
metadata:
    name: hugo-runner-secret
    namespace: source-control
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:URHeOMschdUs1B1uUOw6RP0RHB5agd/VvrBVnNt2LoceuFDSn5QYAI2ei9jPhKsKI1C2KrTVSh7xBqckfczJ/zck6q7a/aaYxvVKemci4PMk1UdMsRfGPcE8moR4VAS62skwpLJ3ybHix5fFi8KyvxluBhro1HNb5UaxeZ78SFlZgtxtBe1OVdN0JrG2Pn0C5Rd3o3D+18sXVfVitIt+1XWFTOac5HYPS2A66k7m7fmi/L8jeO8t8nhgxdgwf5DcFQeVQqE5Qvvd8Dmpe2HV5BJKfQa45tXutPflhGO7TcAQLYDJ84PsMuFIw2OWzp9klYRu8vyKl9voVmGd78Pn1Ay2NFinGDCZpdd9N5u5mpcRBkRfw+tAxEZImg==,iv:PKfR252Af+d5nauvAIqNdE8ygOEvvv3U57MG5gdX1/g=,tag:05ib5kMUOzE6mynWskRIYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eWZGOW9heWN3VVhLL25k
            VUhndWJRWUxGY3FwRVFZeTUxNXRxd3ZUU0hVCk1pbmVyNWM3SEFSMHZwb3pSbkFh
            Yk1OVU1JcHd5VFZnUHVKNjYwN29EeWsKLS0tIEFEdW9zQmZkUHZ5RFFtMWxiMWQ0
            UTR5cjdBZjZPVEZHK0pFSFJpbnNBeTQKRplXX6422aHnUXkOaLeGs0/57DgbjUk8
            PLUwyvphzA/3CXtN+oaMFoFTUxwsC3yterHseiALQawEUzoJCIUwCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTWN1Z2hXTXQ0MHB1L3ll
            TVE5U2JwU1ZCb05rc0Jlbkd3eitCMEdrQVY0CkhnN1QxVU84cFZnb0tpV2UwNU4z
            RGora3pmamVtMUExOE4yQ1kxbk14Z3MKLS0tIGk5VGt2S0NGYTFXSlpENCt0Q01P
            ekcyVllRREpaRmVLNjRhN1ZjTWp6aGMKqHnSrRpJn5mRgOPdK7QqeY8Kn6IoSkGl
            QJ8epl1RBIIVpnswFHUSccgUB5gjirqCu5j4MIKNCN7k+5bsXUG46g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T12:39:47Z"
    mac: ENC[AES256_GCM,data:EGI6nsultrFEi5slt/oPWTC7B2aZme/nNLEuWe781tc6Mwgp+RS8kiKWf3Mu9yQ5rDkQUChOCTWtGfmYzMkwhfm+EyRs76V1XgGFRPz+pDHVxNjWL99bwprOENcsa3AWvHcQCwKN6nFwMKO+2Q/Z1D2oa8G7y5J+jYh6UtufwLM=,iv:qj06NTXsD6/4zlQJnO5aWpMo7b0s93D5Q5g/9qf5xWY=,tag:gNl2O+oown0VzhbDqOdIlQ==,type:str]
    version: 3.13.1
