apiVersion: v1
kind: ConfigMap
metadata:
  name: raccoons-runner-config
  namespace: source-control
data:
  config.yaml: |
    container:
      network: host
      options: >-
        -v /certs:/certs
        -e DOCKER_HOST=tcp://localhost:2376
        -e DOCKER_TLS_VERIFY=1
        -e DOCKER_CERT_PATH=/certs/client
      valid_volumes:
        - /certs
    server:
      connections:
        codeberg:
          url: https://codeberg.org
          uuid: 28ee3535-168f-4083-8d59-ca3befeea509
          token_url: file:/etc/runner-token/token
          labels:
            - "docker:docker://ghcr.io/titusio/forgejo-runner-image:latest"
            - "ubuntu-22.04:docker://node:16-bullseye"
