apiVersion: v1
kind: Secret
metadata:
    name: raccoons-runner-secret
    namespace: source-control
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:cU2PcDDMoFieBgbwlVCvPfyclTJ8k/srwYxEiGUQIgvJZFkciCiwJw==,iv:OT9QESdZvqzONGRL0ZjbelycEmoK2jEY5CU7++ift80=,tag:1zbA+BGJUldxTwYIBQ+64w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa1F0YmxYZWNPZTY3Q3Vk
            NW9oQlZRbFo5aXVuVUEwL3RUY1M1dmZ1dXl3CmpLZFVxOG9JS0RPSHhScnVVVHJB
            WWl3ZGtnZDNJWFlMVmVzUndibGU5MEkKLS0tIHVXeHZ3Vnl2Q2lEeXM0VnhaQ2hk
            Um5CdjVxRnF2SFNDY25ST0JGQ0g2am8KfYm/9REFiWcZosDIuryvt4BmM26+zbLk
            6fyE34twlhnCvUitODTmKYDeJt8VSZ8xQmtYYjBDNlfRd1AlbrhX4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc3I0aDZzV2NGRUh1WWUv
            L0NXc0dmVlVCdHJIZkRmeVVCSk40dlRDOGxFClRjdldMU1krZTRCZ1BNTGZBSFBM
            WnZGOGc5UTY1ZU1kQWlDRlF2aE1ZTDQKLS0tIEJLdWM1bjdoS2lOUlF3a0ZVK3NQ
            OCtVVDhpdEExcjJ0dnUxK1hvZDlxS3MK9Cy7iFN0bOEBQhSPDxXIkfdN10DufqRq
            ebg//rOR6GCKnooyFcv3X883PRVOdAh1gjkznr7Em80Gx4oBOmwVYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T05:25:54Z"
    mac: ENC[AES256_GCM,data:kqWRfQlIhDrvFcKua5d3SWnBS2QMh+g2HkjS8d22221otrGU+EWCTCNPXX0GgwEv0Epd4+xw4n+76aYKQi50763++XqluRCVsL35XP6Z/qEoEkpurtmsmfRnaarMNipfEE+Ys/rZ+tjI/Q/dk0fY2hGF1cNdXQMpz6WL8ycT3Co=,iv:an6vPfjf91MmCkurH4n8LnIRWX71yjGwvVuIw3rE48I=,tag:/GL611t0+yJfkhZoqTo4vw==,type:str]
    version: 3.13.1
