apiVersion: v1
kind: Secret
metadata:
    name: raccoons-runner-secret
    namespace: source-control
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:EWK5fAvL740ySlhwA+VKpx5664HxVus/Z9R726vyl5cBauGDSG0KNrtJguodI1Qg1+5n2Vb4m90QLyKw/lOdiJ1I4GUyIFF3/ftrYgD+izZns66hwyYStW7u9XWxRLOOHtTFIECMGdWHT8IrjTwv3Z8aP3blN+cec7+JvoO3gRqR50tP/kYD9+UFu0nry5K9X3Oqrb8E6u2D9g20zAek81XcKLYPpMDoNpLllMI4x9wRJnsXdupRaXfFn0FZEh6AYCFZx5rjgbXqhMPZCtvdwq8dbP0+a2vb9jFCNMNGjIiKooJ+kwj0cPRyY9lHjy7eqL5AsDG3FuHXGVjvj1+lHN6/2at9N/M6ohZ8z4YSBKnq6D+auFXJ+ry/5Q==,iv:102DuMstNPUvrTDX3TNhPQdrr7YbBtVSw8dUNXxot/Q=,tag:Ea6mqvRbmx4FXxn2U1XIhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa1F0YmxYZWNPZTY3Q3Vk
            NW9oQlZRbFo5aXVuVUEwL3RUY1M1dmZ1dXl3CmpLZFVxOG9JS0RPSHhScnVVVHJB
            WWl3ZGtnZDNJWFlMVmVzUndibGU5MEkKLS0tIHVXeHZ3Vnl2Q2lEeXM0VnhaQ2hk
            Um5CdjVxRnF2SFNDY25ST0JGQ0g2am8KfYm/9REFiWcZosDIuryvt4BmM26+zbLk
            6fyE34twlhnCvUitODTmKYDeJt8VSZ8xQmtYYjBDNlfRd1AlbrhX4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc3I0aDZzV2NGRUh1WWUv
            L0NXc0dmVlVCdHJIZkRmeVVCSk40dlRDOGxFClRjdldMU1krZTRCZ1BNTGZBSFBM
            WnZGOGc5UTY1ZU1kQWlDRlF2aE1ZTDQKLS0tIEJLdWM1bjdoS2lOUlF3a0ZVK3NQ
            OCtVVDhpdEExcjJ0dnUxK1hvZDlxS3MK9Cy7iFN0bOEBQhSPDxXIkfdN10DufqRq
            ebg//rOR6GCKnooyFcv3X883PRVOdAh1gjkznr7Em80Gx4oBOmwVYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T11:27:15Z"
    mac: ENC[AES256_GCM,data:ZXzqJH+4qI11MvRzf+qTjQAva/lwudiUQmJzKemFZpoR1rn+niZGR7vdTXPCKViMXr1AkWzw24Zmes5qLTQxt2UPnODwHZtcMoNzSWSeCptZ/xrcKof4E35dBBcL9LsqA6sS4N9KiCNplt9U6tKT7NTy3wC/7o5kQas4OX2Yd6g=,iv:O1DXtkuyi+1Zk8TyNveHH4lqmmiQFV+CFceEbzDKKyQ=,tag:E8dk/OZdLeh2Nzr5sb3JvA==,type:str]
    version: 3.13.1
