apiVersion: v1
kind: Secret
metadata:
    name: raccoons-runner-secret
    namespace: source-control
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2nhdl3bwkDhcCign0fkgxPBkJ8MWcM/NHaFH2JCFB4YXAK3Cq4LD0giu6N7ldQ==,iv:0q4sM2NKSeA89KU9o7tPq1wmjVVC1HffDr+TgPoavtc=,tag:7J50Re4fDvA7Xcz5iK/82A==,type:comment]
    CONFIG_NAME: ENC[AES256_GCM,data:ItweMMPqg9+x0psMKc8ky0Q=,iv:hxjsD//I6l4CH2ysIULRKjpImUazufnKvwgM01opjAs=,tag:e6jYuGeSURof8nOoW+QFFA==,type:str]
    CONFIG_INSTANCE: ENC[AES256_GCM,data:730DnABk24yxYQ5xfKEqaBTLel5u,iv:HIlvu/JZSMxtr4Nd3J1Yw0DY0xXzdO4Ib1iIHnR3n/8=,tag:Dnrc2pBeHXNCNZKP/aEKkQ==,type:str]
    CONFIG_TOKEN: ENC[AES256_GCM,data:MweNCaVXGN+JZmSVjLVMfDvrFPaQvPsMETOmGbi0JQzJKewhmqA33g==,iv:GZx7yr1WOfcloq1OWQu7cF+IoygYSZmkNC8FLtUL/f8=,tag:Ra4q9VayyvKe3JXiy6nwWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dnh1U292V01DK1VmQXda
            SDkyNjlhNEZKVzNkblBHaGdJWWFHS2R4ZnpFClBZZzRDQ3pLZTBQR3d5c1ZVZlZx
            K0dUQWhMSis1aVVqS2xrN1BiWFNjeUkKLS0tIG04bG9paXVzU2FNRU9ONytlelhw
            VUY3aHZJblhLdHNVQWM1NlBhZUxQdzQK8i6m7WCZOUTJm8PrEsz6vDZw6jBMHq16
            aCWHM0TvIlwY8J4hAv1wjp3JFqaRu9rTuYgP+rg72GS3CaaZEz6L/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcjZBQUJTLytuZzVPVE4z
            Wnl0aHlrblhhUFJKZWcwVldoS0F6OUNZTTM0CjV2blMwam5nRytEdEdPUThnQ0to
            S1hXVlhsM0hTd2p0bGlYSlJKeUhTalEKLS0tIHk5d3NpQk1WZjNOclhlazNQVXhE
            QndlaG93eG5mMW16dmgrcFVKcytWcE0K2l3Bvt5aylJOdqworA3Btz0IrFSFLeyA
            A8NklU9Rwb1S43JKm7ISRKQPxaCccAGP28XFqLOoFw5/NYX4mD0j0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T10:22:41Z"
    mac: ENC[AES256_GCM,data:LdH0Zbc2ctYza1L+kshupvwH4qDJ2REchHwIGm95704xcUK7htrFtXS6yygPYzM+PhFAhE2YiuMs0EBqOFVl+Cf4mK27oA+AaRCF6OntjP3TBIhpvisOqDpKLrU/FpTUBPU8hAm/8uCDaVVzrYhiE0JFygEUNie5amHJrloRcaw=,iv:z6KgXxxQ33mJVBJQzqj2EmMPjUIX99KOc/G0VGplg8M=,tag:XKsadKA3yGejyteLt3mrwQ==,type:str]
    version: 3.13.1
