apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: alderaan-domains
  namespace: external-proxy
spec:
  endpoints:
    - dnsName: immich.huebie.family
      recordTTL: 300
      recordType: A
      targets:
        - 204.168.137.124
    - dnsName: home.huebie.family
      recordTTL: 300
      recordType: A
      targets:
        - 204.168.137.124
    - dnsName: paperless.huebie.family
      recordTTL: 300
      recordType: A
      targets:
        - 204.168.137.124
    - dnsName: nextcloud.huebie.family
      recordTTL: 300
      recordType: A
      targets:
        - 204.168.137.124
    - dnsName: mail-archive.huebie.family
      recordTTL: 300
      recordType: A
      targets:
        - 204.168.137.124
