apiVersion: v1
kind: Service
metadata:
  name: alderaan
  namespace: external-proxy
  annotations:
    tailscale.com/tailnet-fqdn: alderaan.donkey-betta.ts.net
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
