apiVersion: v1
kind: Service
metadata:
  name: alderaan-proxy
  namespace: tailscale
spec:
  selector:
    tailscale.com/parent-resource: alderaan
    tailscale.com/parent-resource-ns: external-proxy
    tailscale.com/parent-resource-type: svc
  ports:
    - port: 30070
      targetPort: 30070
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: external-proxy-to-tailscale
  namespace: tailscale
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: external-proxy
  to:
    - group: ""
      kind: Service
