apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-secrets
    namespace: networking
stringData:
    appKey: ENC[AES256_GCM,data:5GMyId4vxv4w9wgcKB8uz2sAxPpD5cDj1bWr46GtsuGzOFXHxQzxo/DB+aqTPFrPab0/,iv:0AkxfpWwACrnk0oomKEj49j7x3h4nlD1WouMcIa0m4E=,tag:Z5AK6WLeuAsjuv/DFZNurQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT3J3YUtnSXRhTmxNWjRS
            QWU1elFuclBhVjFOWkxiQWV4SjRJcFIyeVJRCmE3TDAyRW5jbGFoenJNWnM2eHJM
            NWNoM2NKZmJMdnNKWUFiTjJ1SEhPOGMKLS0tIGdVTm9BMkhralNNTUhJdEhKT1ZH
            UnBPYTR1b1UrS1g2QlY1RlYyTmF1cFEKNNLCjpvtt8leeq9dmFs5owcnauP0rO5X
            pdQxilE1fxC7SHVrF8X/dg9Sd6XvXGFk6+sBjRmpDcvZxxHDYK0tKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqY3ZRalNwNUJteS9TdHpi
            R2NCcjVEa3VKWVVyRHpFTVpNRExNbUtIZDJZCi9YM1hqNlh0TVNHUFV0eVI4ZlNq
            VXpmQzFMb1gxaVFZYnFIU3FPL0Fhd2MKLS0tIDdqTjZva09OUlREY2J6dFl6YXU1
            TzV2bkM2UmtPWmxmT3Y1ZjM5SllGOE0KTS0mxObtUL25NbxTS1quQIJIiy+5vY4J
            kskZ3Qittr+UbDkUyDSIrkv06m+WqwG+XbGxWcVH1upCaWCG7X5yZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T15:50:09Z"
    mac: ENC[AES256_GCM,data:T4ezd9oJmfFtAaPHfucimU7OW8eEAPi4Q9UzCwCmMf5v6/0XCFn11zDo1nBvbnMhyE+MFG/IOYGdemSHJJNfsdcKudpOeMnfc5Wb895DrBuQFRKYAsf1qqT+rPE+UVnyesuu3VAx6y9ZNtqI2Zf/pDY7PY8mIeZ4j9/++BHKreE=,iv:f+Z5FPtoVY0CE3Eiu4aHq/qPBhDo7iZCeuXjeIxzWdU=,tag:lgvQqsaHY6EJWKob3umq1Q==,type:str]
    version: 3.13.1
