apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-tls
  namespace: traefik
spec:
  secretName: media-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    # arr stack
    - radarr.tituslab.dev
    - sonarr.tituslab.dev
    - prowlarr.tituslab.dev
    - sabnzbd.tituslab.dev
    # audiobookshelf certificates
    - shelf.tituslab.dev
    - abs.tituslab.dev
    - audiobooks.tituslab.dev
    - audiobookshelf.tituslab.dev
