apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-tls
  namespace: traefik
spec:
  secretName: media-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - radarr.tituslab.dev
    - sonarr.tituslab.dev
    - prowlarr.tituslab.dev
