---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ephemeral
  resources:
    requests:
      storage: 200Gi
