keys:
  - &corellian age1zvea0a0g9xkzgc0umprter9kd8c9f7je57psgnkjuvv963x5u55su5s80s
  - &titus age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
creation_rules:
  - path_regex: secrets/corellian\.enc\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *corellian
      - *titus
  - path_regex: secrets/[^/]+\.(enc\.yaml|enc\.json|enc\.env|enc\.ini|enc\.txt|key|age)$
    key_groups:
    - age:
      - *titus
  - path_regex: talos/secrets\.yaml$
    key_groups:
    - age:
      - *titus
  - path_regex: talos/talosconfig$
    key_groups:
    - age:
      - *titus
