apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: allow-access-scarif-vector
  namespace: object-storage
spec:
  from:
    # photos
    - kind: GarageKey
      namespace: photos
    - kind: GarageBucket
      namespace: photos
    # photos
    - kind: GarageKey
      namespace: cloud
    - kind: GarageBucket
      namespace: cloud
    # ai
    - kind: GarageKey
      namespace: ai
    - kind: GarageBucket
      namespace: ai
  to:
    - kind: GarageCluster
      name: scarif-vector
