apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  name: scarif-depot
  namespace: object-storage
spec:
  replication:
    factor: 1        
  gateway:
    replicas: 1
  network:
    rpcPublicAddr: "10.0.40.105:3901"
    service:
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: 10.0.40.105
  connectTo:
    rpcSecretRef:
      name: garage-personal-nas-secret
      key: rpcSecret
    adminApiEndpoint: "http://10.0.10.10:30290"
    adminTokenSecretRef:
      name: garage-personal-nas-secret
      key: adminToken
  layoutManagement:
    autoApply: true
  admin:
    adminTokenSecretRef:
      name: garage-personal-nas-secret
      key: adminToken

