apiVersion: v1
kind: Secret
metadata:
    name: nas-ssd-secret
    namespace: object-storage
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:QaOuiTPuy6I7Pte3lnM/Mj5viHdBQgAtQIck14Sf/61GiftkuaHitKL9muMvublCxOw+qbj338XhXygsBw0z45ltDPseq6/Me4wf7jbc+pfis8UeETX76fvmG7w5alqgIvoh7REKCJ13TJmmScivaW7XdgYNaVJIAg+CN4qpm5o=,iv:2yuK7jLaSQ2tje361p15cXdPl5hc/lcrVPIElCeBd3k=,tag:5M3S36vFQY3/quGtxMClgQ==,type:str]
    rpcSecret: ENC[AES256_GCM,data:V59OZQ51O2O3/zFsewbSybG7DQA/cUJBLAA3FMsDVCIL4jX465lEnCe4VyyrJAc9l0OZgIMPuMn6SE7kMjhgsQ==,iv:0b/d9vxcYu7QWwRKQ/orYA2uXX0/sdJZhEN+qa2Dctw=,tag:BAw0bWe/jUswpX2kOwSfNQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:Ett2T4rWRxA1XCB9bPviXWV+GuE6VZumiWC8U3uqfHg=,iv:z5Tk0D2SvpR+giFJ/7QxPGpTk+m3ZnkMkRTTLV+EHBs=,tag:+RmW/OYqjy4CoGIrKmw5wQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVVIZzZpSWgvck1KSlVh
            bzRCcjBhaUNFbzBkZVVJaVU4ZHRNV3lsUG5NClBLNWN3ZlF0VGNlUDFBTnBSbFQ1
            WEEvQ3BXZEkveHpUMmZKWkV0ZlorRk0KLS0tIDRWQTFsUUxQbU5BTHZ1emNLZ1hy
            TUlZU0gvZVp4QnVUaXp5S2F4dlF3TWsK3gbzwAAIgu8dfjAxYUeUIGASS1XotlVe
            x81tYEelc637KYu1EOTCKFWtqv6LGRj/DRs9A0md5UpaLkCKpDQPDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZk5CUHJYL1g5R2xvblpU
            Mkhod1pKQU5iWS9RbmpGdS9qYjdXUFpRdGh3CnhCdUl5Nms4c0k4MHFDRDZtK0pV
            U09yZmxhblRJNTVEOVN3N21xditwOE0KLS0tIHNnQTIxTEZpeUE4bjE3QWI5UmQ2
            NWIrUWZueVdxWmFveEdJS0RlY3VRMWMKxLnzxj2q19d/TfL2d6LI7sBhd7RnvH+8
            RhrSc5ba1+O2MSZKdVVUwH7EZ6198sl5H2QwMyoWJKddRHYRxryOgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T14:52:12Z"
    mac: ENC[AES256_GCM,data:K7u1xtNwlpt9XunAvHu0QbYznoGowyp7yJAeEWFbgMmj64rPm4qyCadC3KKnzFBRAZLY/EsbqP881m5SobmCYUBcAPy+9rPqlTYWUpOWHYFnfDEh9cEPjLeVGQSWn75EOkkDlaeZLCDeWvu0XTGZmmemR+Sam2KQC+fl11erAbo=,iv:84lN8xOZiWGqeD2Fl7yOTVj/YaTArIcBjzk44gGriT0=,tag:nO4uMXHiaaEAN6gHWAasVw==,type:str]
    version: 3.13.1
