apiVersion: v1
kind: Secret
metadata:
    name: gatus-db-credentials
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4kJ33uI=,iv:LPg4l+Ob+vMijC8YcaRiLfwEU/rRtRemlizCa2Lxgno=,tag:evjJ3I/94GmYexoiTrJNpg==,type:str]
    password: ENC[AES256_GCM,data:RYZp+QCs4VR/Rjw8CVGPI444kONHyqmNiO0vbNHujz2dJJ/PNcPN9cHJwTtNmCNoG20OrtuJzeVs/nYhdBgjwQ==,iv:W7srNPgeg+EMdT7iS49kbwLMvRJuOOPQJ30Jz2gTDa4=,tag:YD4ohR0Wha/tSR1xD4qGPA==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:Yxmien00KQfBGmg2l+jU+b7mIVNDhyXIDoLwYqHWHOyfj1DY+ADiMgVu9D/A/J2lmYeqj8Qf7H5oruGai3OmpJGKfEfaLV+GcczmGJV0qm4c1TjgVtL4zTqzZ/Xsw4dxin1tIdGvHqYD8EbDpavMKZcBrW992Rup69IyaAE7BQrVdKO+0w==,iv:ACWweTQuaXaW9CzV8mU7v8KvkSgYSAANmDFKGsNUYnU=,tag:qFR77qdHM1lteovku9HgwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z1loT2FJSlNoQmZxTlI0
            ZnVjSzUzNXlWQmJpNUExbVl0bVdKQzJSQjFzCjJ1MVJGUCtMNmJXcmt4Kzh0S3hF
            SW4wYzdTSnJJZnVvVDRDN28zWDI5S2MKLS0tIGJsVkZ0K2dYc1crZ3BNUWdPMXBy
            WE91clVEUWE0b0tCRGExUmhTd1lMUVUKQQFG+ZagVI2dralUm7N7OxY4VtiFqIEz
            g2f2KLTKwuWX3JKvyO6F/Pt68uw5WZkAhQjgz3hunI7E2veEA/gADw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTW9NVndoZW9NSnA1eVN1
            M2FUWjJLbjJtNk1xR2tBeUtGbGJ4b3gyZzNvCnM1MzZVWkFIb2UzcW51WC9aTTdH
            QXNCdHVjRnV5SENsSmFkVng1UnRDNncKLS0tIFRUc3cwOHZUMHF6aFk2UklwVW4v
            eDA3alBmV0RrRUxvc05BK2lZWDVGS1UKXbRGFdwCv9rw0x6ealO8p7et1aV3COZD
            pjo+jiF9IJxSRXw0lAoymi3UNBDogsNFmfJIZKp978wDA96iackpcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T19:31:34Z"
    mac: ENC[AES256_GCM,data:1FdTW43sGTjy79l+wYidp5+2DYSvckRB2jihO2hygvRA4suBqnqTIT6a4tf2QpAeaaOmx3NZU+Vf9Vqv6HTFDj3KS51pzhq/Hhowr5x11mr+FSdy+E7aN7KpWmCfh+a22rN5YuO712A7+NxmUpqkb+Kg9ufkumqQ7ELCWoeCGAU=,iv:4Yrx/J4p2AZ8KQJvcXZjGpXXf60/8ITUzEktBOwHB94=,tag:7HQohqNnPtfLVEovjGEwmg==,type:str]
    version: 3.13.0
