apiVersion: v1
kind: Secret
metadata:
    name: gatus-db-credentials
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:G+iPidc=,iv:5rEeGcJOQFVDiZTDWysdFKi+l8AgofPzezl3/t3H9WQ=,tag:GwxPeqY2hft+IA05DMui/g==,type:str]
    password: ENC[AES256_GCM,data:XZ6idfQ7Zo2J5s11iMRjwnYEy2s2Rs5SHyZrwo2qF9xxYV1Xfy3aDoVMlhg=,iv:lrBB0igsJVJrlRsibGfqi57Ev/cU0ciGh5vfTlrYtTo=,tag:T+CMJF8Sm6Pdkvmq/4+w7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WUVieVVHQkZEYWhlR0My
            bHVBdWRZNUpJZ0FSM2ZyZDE1dTkrT1FCcGpRCjJpRk5ISlVZVVF4YWdDcDUvcm5E
            bzRPMG41M2l1S0NlY3VhZUgyZTU4ZDgKLS0tIHdNNGJ0VFdVSnRseWs4dmpSYnF0
            Um9xNVIwYlpOankwOXgvZVJhRVRpQWcK7nQcNtMAVFLPn1s2PKxIZeRKcXE/kHGf
            7+aI9wp6smB/kmJ1tn8vVP8dp8LQ1+hjRXDGAqyuHp5WN9YSzGhtCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MFQ0NkFmb0lqd1YwV1dT
            SERNSXpoRHllZU1HV28zdXlOcUFabmFQV2xrCnYyaVNXRGdIcEkzR043bkh0RGow
            MVJnbFN4RFdGWDRCV2Z5SXBFYTlHRk0KLS0tIEh6ZkZIeHNEeDJDbWJhQnJJbEpt
            eU5KamlKOWo0YkJ3SldjQ1Y2eWZOTFEKzGm9Wn8Nvhr35mraecrpAaobK0vbCyd1
            LXoSlu5tcC7f5pcynN3Uwzd+eQysqiWvP8X57pp2pTTn9vd7BtEEjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T18:58:50Z"
    mac: ENC[AES256_GCM,data:S3pepmI0ZA1hGn0xNVkk0tYEXzwPG3snuyCdsCrJl5gfO27aF4xBgfyrjQRdYJUYhgtPWb0Dh9mVTdJMh54xcG3+DceGzz2b9OzJx35NubocfvK+lEn7fH/gBJtgIeltiDMZ2mtcJLZ5v4/BjVRJYeKXYH6fbAO0W2FgktV95B4=,iv:iO4NQUhpzGf+1jqbukCg46gVVC+u6nvxF18WVzBQvYs=,tag:YkXHMwpOuuHsFA9e6fBnIA==,type:str]
    version: 3.13.0
