apiVersion: v1
kind: Secret
metadata:
    name: gatus-db-credentials
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:WdxbG9g=,iv:EwRV59ho7z/0y7+9vrtwBOwr4pIw2530NJ1HtfJn6TQ=,tag:Uda463iTJ54gLDAawicv5g==,type:str]
    password: ENC[AES256_GCM,data:xT8SYWjHwkImiEFbzl+HiXQI9IU6Iy2gz/Wdfy0U9B6nj0+PhBIKSkyU2I4=,iv:NOZSaXXivn7+FCeMBbgMZnVFOVCiNiTJzCMjOmt7e2E=,tag:HoVWpd3JeK/2cn9cvv9nVQ==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:rqmhGwOk55YdPc1nqha1uectxKauuW+BnDCRWgrylcln1wfmsl3kJwunSiMzjI5bA/nQlRueMVp/J1HTswDGpVRLEs0geyWsXMQs1h9//6ga4C5lbdbUQD69iknzK+IXwaLKC4zBobhNFbd/IypMVug=,iv:B/u2vfncZtBzz1g8DzxOWWcPPqGYuCs3UUqC96tqGs4=,tag:P2l9fvHOMUyd0NbFecT4lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSlhJNXU4VHpuWlV6eGM5
            cDVTMjZSRjVjQ1FHb3hhZ3NrZ3ZHSXBadmlvCjNDV2xOOVA4MllMTGo3MitsTG1M
            Q0RmMDNVUDQvR3dmRmhRSUtvdkUxMHMKLS0tIHphRVpmcnJDWmgwcXQzdUxzcU1x
            MEtpbmp4amhBM2J1L21TVlNqLzkvK2MKbHT2c5hqhFfrrV5UXf+mMrrgic9SzE0E
            bo5EtnUnVu0cIq1EaQAWmj5sgB4kP518Hl52m+5oACwwgNyEW3LGAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUZDVU1VTHNBbkYvRTZI
            KzNaNGJXZnNzZHdoZnZhU1JYaTlkam1hdkFBCitLL01IMkZwR1JvbUdraXN4M0dF
            ekN4VVdZYVdCSXAxT3dJTjZXNTIzUDgKLS0tICt2VXFiN1F5UFRhSUlwQ0lWM0xH
            UTdtT043aGdpcUJLd0diSlVkQkpGbEUKmwJvEzhOXFWVHUomfqe5uAGRbtbaf1Hk
            +u1GNmRx6u0Y/ikVJ8z0snk9jy4cdtxb0igKyhm2+n6m5puCG4ALNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T19:12:36Z"
    mac: ENC[AES256_GCM,data:8rAiM+FcYujPwTV/Jgz/Nla2/jY93cg6Mw5FMZFL95RxVGQJuDPhHeu9kN/XH7A+pMWAx0q8NFZJH2X4yE4TwlylaGFPYfs+DSAXVExPG+M0bm/dErvZpayqU5VHHsVKIriL16PDuJy6LE9f9vpwquV+PODte9Wm9Q8lsfb5a7Y=,iv:VvHGStJNKUM6kazY7Ul4FT6sSBn6TPKhfJGKDaZXGS4=,tag:ZvM5qgCLmK7Ck52e/qrqeg==,type:str]
    version: 3.13.0
