apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.21.1 
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: networking
  values:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-admin-password
            key: password
    # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
    # You don't need to set this flag, but if you leave it unset, you will receive warning
    # logs when ExternalDNS attempts to create TXT records.
    registry: noop
    # no ingress since we are using gateway api
    sources:
      - service
      - gateway-httproute
      - crd
    policy: upsert-only
    extraArgs:
      # Switch to pihole V6 API
      - --pihole-api-version=6
      - --pihole-server=http://pihole-web.networking.svc.cluster.local
