kind: Secret
apiVersion: v1
metadata:
    name: litellm-secret
    namespace: ai
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:1hRU4PknlLxKz0v53SLA9CTLvm+tsKFMgqBQCHFzpfnlliCq+j0BkDhvsH3yarMrRByhc8b39zEAsvWJ7wA6ztR6gQ==,iv:IjSDtZsZj2YpMX+u3/lTH7evrivvjhKX4OzI15+6KWs=,tag:sOFFJV9dMV/nm4v3Af9lbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNUhOam8xWmxqM0F3N0JH
            VW53VzRQU3poSUc4MnRGUnlvenNoRlkzS0J3CjBLTEtzejlncDJZbFpMTmh1WjhN
            Z25waWhxVjBHQmpVbExXaUpmMUU1V1kKLS0tIC84cThTZ0RYbHNscVI4WHBONk4v
            Vk12TWcwWWNkTzNzbnM5SXdvTFd1amsKsggilaMa3dMyV2v/mggOlghZS3i3QQ6U
            AjTS2jqnKA9LadeYLl7IVkC74qyAzLlzPovFbkHE4Cs8AdHXTXNW3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubUlFZTJXWnZNQUJZTVF2
            WWM0ZVQ2TmlBV2NjcnhwbzNVNHVvUlJacHh3Cmxxa29ibTZRQTZ0Z1NFSWRQa3JL
            eHV6V0QwNXZJcm45aHhPWlp0bTF2azgKLS0tIGZQZC9BZnVaai82MXNoM0UyTklM
            dHdDUVFIRFlGM0trQWpEZkw0NmtFNW8KcqItoaGfn76NsOXDbXW2WV9F5xmrdn7r
            7puFr/Oxqzt7KXCK2ThMu0GKSC87qfFUQMc93ozUjoH37rKwL9lkSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T04:41:16Z"
    mac: ENC[AES256_GCM,data:3WSgy9xLAbOU9nRULSzg4BYo5Xi/sx/4Lpu20V3ZoJyxvJMDRe1j9T4w6W3DHTr+bbXRme7BQEiHE4y77ATZq7HwoBY526wtVmDpdh9gCBxvah0tzqmMPVsv5WVwk3GtcgHlN0/2sk0OKv7lZEPwVOq1Tmp+gVb1TQSmEXwLxDQ=,iv:L9KUQOd0dl++l6vFL8nyNXS7wPyC3bmhh0AVqR4TEws=,tag:Mc5uts9WbHyTiwvU1MI8Qg==,type:str]
    version: 3.13.1
