kind: Secret
apiVersion: v1
metadata:
    name: litellm-provider-keys
    namespace: ai
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:6ThFbNZJoG3RuEZFp2KewOD4Gs2bNG0ktLGa2IXdc/NrnWjZ2288N51MmPXqIXj6+RK+oRmGlBklSAluMRpGxH2WyvDf7vi6qQTmeSWjEkj3uzgTvgecJBw2pgoC7ikzCLHpgz59SSjmiH3w,iv:vUhgtxAJkiy3hitmbtOAdC3y+Eh+Q1Fq5R8h2EzY1hA=,tag:VLLcXO5yot9bMNgXqtkUAQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:gYfNL/Q0TLOhd/uuSuLUOyxlZNEowjYDOnDMBsUpl8GMWsdtkoAXjP3rfonlthZS63G7ueo/KaT975UhCnlf/aPtRAt2vlBm+718nANCKKww1yHrbl07oNvzF08lWUP6hDBxLer4+ltKLRCx44/5zJreHWrqDNa4dJQsrXaFT3H59+u6t3kORYbw1cl7ksgXLlaVCApsxIX0Utlpif2RBAmR47Q=,iv:simuhIAxUOioWDoR3jvfj7FaX3USBx+x8v03Ax75oKg=,tag:WT09f+fg6y4vmGd8dXt6dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NHJZQlByMjFoUk9MTzhR
            QU9OUmlRM0cyVEdNYjVBaXlnWTZRNVBvb2hnCk1Ic2xTbjB6dzc0T1JYVGRMaHMz
            SWU3djJLckV6TDNSM0VCQWRYYWM5TEkKLS0tIFV4cVBzc1hzMmVJekxNUGJwK2p3
            R1E5c3AvVHBUM3hyL0JxOFBlRVc3VkEKdSx9r4V34gjbRGezyxYONp+OJJVYFvpQ
            jKAGQ+oxAss+m6acbxogIfpWObMGv/iX78GDmxweb9wNe4EefSPDfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVVKc1R2azBFNWZtRUlt
            MExiRTFGajBRMU1oWVh6K3JtQmFVVS9MbTNnClBJVnNQd3Y3eVVGZk40S3VUMmFX
            NHFUQnpGNVZKWkZuNnhaK1ZPTk5CeUUKLS0tIFEvYkJyRFY4RCt0YzhpKzA0UVFo
            MmF6WG5WN0l4MTY5UGFxaUVtZWFYVVUKBz2njvJ/v4pQysTY0kk7sCJbn4xRGMxt
            wcEUomue81RUUKeG+YLgs/PVveOHGDnEbjPmpx4S4wCggCwlQBdUpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T04:56:33Z"
    mac: ENC[AES256_GCM,data:MPEacwDWrXaKgEyszBgp7gPI7tSOXsyRgsaxPv2RgjY/IkLEWlq+qutZE70ecqBId5FrwUeRfQexrQX4lFS4BlpnPlCszLNBg9WCFu4dciNUMwIRqMW5jQ7osWdTy1hsIiqi0L4Ugwv/niqqjtCvkVeJt4UfzQAY6oi3ZU0YgCI=,iv:sD1/OPcmadRB20gKRSuJlDXHSCMbX4ZcDxLmATEt1GU=,tag:aTIgsbn1sA3NwbqEJmd/7Q==,type:str]
    version: 3.13.1
