apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
    namespace: networking
type: Opaque
stringdata:
    username: admin
    password: 9hsp5FAidJb4KNBHqsinjJpemEa5CpUCKT77TcdSU
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVm9sN0lNNkMybU40RVo5
            cG54aU45Y0Y3Q3EraElIWS9VaEppbGdaWGlrClJEeEV6ZTdnWlNPcGhMQzdmWGp6
            REtqbWU5REorQnpwaGF4R0pBM2dIeFkKLS0tIEdVSWFzOEMwTlVUK3g3WHJQR2wr
            RnZjdlBNdko3TVY5RzExemJqOUtkdlEKaUUma2FBc1RFHYu6CAJ2IBRzT98bvuND
            AipjffSlP/H5rQaewn9gJ7ntWKms2TwF8zUyUCcY7h4c7mTLgQeJow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZlNlbmpXTmxRdjRXSGVn
            L2JGL0FHbTB5MTQvWFB2SUc4WGdENWM4ZTM0CnAwRE5OK2lzY01aWDlBZ1ZKV01l
            ZWZ6UnM0V1JNQTBiMnUwbFZ4a0VWOUEKLS0tIEdjYTd4TEFtYm1CazdRSTVkYUx3
            Lys2VjA4ZjZ2VHl0NUNkUVNPdDVsSkUKas18RXXcBFLsxm4SbrdYoCT7WVWuFoTI
            fbYPvJo4iNjM7IgGCZ8QTdRMzrN/h+7xqSqh6PzJRjyor/n7PMPurA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T04:28:39Z"
    mac: ENC[AES256_GCM,data:GdEVYykkYt9I7gz0UsHxIGDMZYiCpJvYUnIptlhzsDRiaiFD4f5rhq5q8V/E8/4SOlbxdxueMhlqwEeLy92Ch+P4LliP2EL/Uv3cCAevbNdpTbhqwXIXZe02ZWfdbo6mu8EtZiQMzGZjq75iVzg+olPs0CxFesOu3ujfIDQmLvg=,iv:crL3ANuW7OUq5ULFeVa0f7LDMgsMyqmyccnihvBdaOg=,tag:sfeH14XUP6DbjqTaf063JQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
