apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
    namespace: networking
type: Opaque
stringdata:
    username: admin
    password: k2IrNU0ebalGLDqUY6PpIggWXbX+QwrdEA/B817oz38=
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOGlJOVcyRERteHU3Nno1
            Vk1nZGZDVWRYczN0cHppZVFDZTlkVHBLZXlrCjVLaC9pWERENGhNeDI1czUwNGF2
            MzlUbzhkVWl5bXpMUTg3MmtKb2RaR28KLS0tIG9Nd3NZbW5tQnlIM1hnZkgveTdo
            WVFZQUlHSThHQWxTakNManJyam9BL3cKnqwAoxTUe+mcjFJgVv3L9kB/HsI3hsGk
            7Qv3wXdDVu+p5lLw2liZ3S7DtF68l9yGCEoW3GX47mOMoXuYbXJHng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWkpRY0lrRWcxek1wd3VC
            Qi9uVWk3a0R5bWI3aEIwbUduWEZWbTRuR2xFCjFSSXJQcEY3RlJocEh6WG1XV25X
            cWRGYmJjTlFCbmw1akpPTWhQbHBuUzAKLS0tIGZ1N09sSW5ZcGxLc3VpcHNnV1hD
            WEVBbDBOMTU3dlk4aUwvNjBBRExhancK10+12m+Z2yqF9jdFrDvCWp6GaK+EF6hr
            BFd3i9brUVstG2ZII5NQwH6iHwvmDpq22rtGfnmDKHj/EyrbVlPHhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T04:19:47Z"
    mac: ENC[AES256_GCM,data:NeUvYykVzpiWupmlJFDTejJZau1QYfVFt4Gtd0/lP2YpSiwNiklN8b7h9aeIJ314IWHmglB1ywa/qMcN2ztkLffQdYButXve2V9ui+8sFz8F/+P9EpME07atG/HaYrpOrL9+Vu03uArY02z1yCqZskVQKQeeWgHgO0wNkkO1A2o=,iv:++wf2fBn7Snif0m5T4Hcl0j4C4QT8KE2upseDCi/bAA=,tag:DxNE6JqRQKzsYJLjqe9yuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
