apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
    namespace: networking
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dJ9XlrM=,iv:omQaKtzA8R3EHTChptkSprttWMYXY0/bkO1w1fZmNq4=,tag:JeakJueUYecAcLyMIvdTKQ==,type:str]
    password: ENC[AES256_GCM,data:R5l89K6UkRZVZ4hkl/GLvDSdyMm4wqY0NGpwfn1JeJCDeyPtlhdU,iv:2jjmydOr51ExqQIgGmBmt3GEj6XKqSGpuQptx7pPQgs=,tag:14UGyNEcICdfTnmrUwlfXQ==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU3VLcHViUmpYd3RGTUtv
            OUtUbHQxQWNpdTNGNEpRcDhqbUtWamNMM3pZCjB2d1dZWHdudm4wamFrQkpYYkpw
            ekR2RkdEMHlwbGhBYjBVQ3k0dXRJMWcKLS0tIFliWTRMT3kwUWdybG4wZEdwaG9p
            ZUEzNlYzMUFGeVY4Y1gzeVAvMkVtd1kKCEW+tqkWHwHBSxezZOCDZbIbOrAG3Dq8
            QF8fPkUyh5hyZDii2r0SOH/9yYegI+Um2OF9lD9YatkDVHB0AAEf3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5THZBSXlEWStuZWR5V09r
            TUVzU240MnUxbUQvYTd2MEtuV0kzTk0zVVE4CmVBWU1SMmlMbmFlVkp3S3RkWDZX
            UFBwZkUybkJXYldTNkhWT21PNWQ2NHMKLS0tIHZlVHJ2SHAva2lkVk9GMVZkUW1X
            dElrSmFyeUZOVERNKzYyMjY0SFc3Y1kKoKrVlIHww5MluXEj9kFFABymGvDp1ZHY
            k8eU58cwSa9Xy7wlIdeegutwy7Ec8ZqR19WF39ovSQYIitWMwFuFUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T04:34:53Z"
    mac: ENC[AES256_GCM,data:fDDDtotDpNZfQcO3Kagrd3FJBM3BBT+4pvRRdxuWPkvQHvCiXw6ZuVrOBqSaOCfGBKRTI0hnfHW6MkNxolAkFZnKKVXNU33jO7ragG0cwDJy3B6HEGVOFQBgefIKRAUY3g13zOHuobWs60ysHF54hbHEAM3ut6LdVK+McBsbUoY=,iv:7FQBl/m79t+lpL4R8Fvibkgt1UXnhCnwkT4mbbsjIsQ=,tag:3pFyFqoEmgX4jaRlmUR2JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
