apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: 2.35.0
      sourceRef:
        kind: HelmRepository
        name: pihole-repo
        namespace: networking
  values:
    hostname: "Pihole"
    DNS1: "9.9.9.9" # Quad9
    DNS2: "194.242.2.2" # https://mullvad.net/en/help/dns-over-https-and-dns-over-tls#server-locations
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        lbipam.cilium.io/ips: "10.0.40.100"
        lbipam.cilium.io/sharing-key: pihole-svc
    serviceWeb:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        "lbipam.cilium.io/ips": "10.0.40.100"
        lbipam.cilium.io/sharing-key: pihole-svc
    persistenceVolumeClaim:
      enabled: true
    admin:
      existingSecret: "pihole-admin-password"
      passwordKey: "password"
