apiVersion: v1
kind: Secret
metadata:
    name: hetzner-credentials
    namespace: external-dns
stringData:
    api-key: ENC[AES256_GCM,data:RNEXWEksyxnBqdRpEC7vVypHwQERybSL3cYlOZe9+zBg6p7cpprrimhAfsF/eMG3O8mbkDDAzsXF/64NXVNT5Q==,iv:bqcfgUfsmMNzNDYv538ogWzUQh9IZEaSyl7gd5WQX5Y=,tag:S5kOuFTW1k6SDgUggXWgEQ==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUcvQjNXUE1Zam1UQ2dC
            RmFXTlJjWHdmUWpRTXhHclE3ZFRSREVtN1VnCjNxUjJZUjBqckwxTFdidyswZ1Fy
            bFhWdFpxNnFBSjZFcUJzYnIwYkNoVGMKLS0tIDhoTFh3QWVwK2EyZkdhMWFxbmV5
            N1ZIUzMyUXZhRlN0aEwrazhreXd3YzQKk6WPEUHafGIsU7ix1dRDHjliSANXA40I
            bfstdteu97eL0es9YLJvYhB0zwI5QTmlaycqDirb+OPoQwedLO2acA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMXZiZzJ4RDB1UEpWVEJ5
            eEd3WlNOdHNHUjNCSERDeEs5U21rRTNIazNjCkxtY1dRaGR2cjVrVDduQ3F6cVVs
            eDhOTjZtQnB1VWR3VVVWNmVwYmxLeFUKLS0tIHMyY3FtTmpCUTkzd2k5R3lreDVB
            dERES282ZEZqVzBsVHBldXJ6d3BpM1UKplMW36aSV+l7ycQtlRgeJz3LQ/I6d7vC
            zQj33YotXYYwdQiQVzzgimoglfAcVQlYiOwKWISYGd9Y45LjfZhGJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T17:41:35Z"
    mac: ENC[AES256_GCM,data:j2qZjPp7WbSvhalxDoKKmH+xnw31j1EOo15/dvnBnrbb/lhOTpxbL6BTsL/x4mcqohSk87z7MrSzkI9zZE2DAJgkqbCM4RN8qa0B3V8wsVCmOqtefvA1xaFAkrSRkXXFyluBUDsnnHEsY1iLUA5kFTV/m/hSeqFw0pJRTxIL6Gs=,iv:A6EKrBUq921TlaSs661RUU2USsiR6CMOQcPSg/l1htM=,tag:MYi9FCetbD7DGPcgegIkZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
