apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-credentials
    namespace: source-control
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pKzShCnuH/Ey,iv:dq5fZHkMAgsiaNMzpKC2e6PlBcvi+UDco48xJpiOH1w=,tag:Om22DJy/dzhHef5epEJyfQ==,type:str]
    password: ENC[AES256_GCM,data:UNbAnpUOTwz9br5lQjiH8os3d3g2rNmQIYkHCDn57s0=,iv:iw+TuBgKfQwwLKvuWQy+iFywO+t8AQaz3jOkLwei5rs=,tag:D7k+ku9nnj1upUOM10tODg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5enhnYmJBWURZRCtTOGp0
            SXZpTFdBeWZZWFE4Rm10Uk03L2pNK3lTVEFnCkxRY1g2MlREUTlmaTZDTUxUQkZS
            SXR2RkhROUp0akxjMlZBRnpwUGFFMkkKLS0tIGVuVE9UZlpNbHQ0V2FNRVo4N0E1
            SEtaMVpaOElVK0J2UGVtQ0loem03cHcK5DMwReeYMJGuYtpC20RqIWeEH5T84QA5
            WauJNnCEJy0+ivwgQg2NkTMtzyqxbupjohaqiS+8EnpWeteBV5G05A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU3FRTnN0WHV0QXVUUUc1
            T2R5US9PK1drNDMzL2tLeUtaNTU5dVp1R2dzCk1RQmVsYTBTMWhzNy9mUWVmUUVq
            WFZDUnhyRzdPRm5DZEF6MGVweTlNSXMKLS0tIDR6RTRGMS9vaXhzRWRUSjdvNFVn
            VW1pZHJLdWprdHNoNGNVN1RVSXc2OW8K/zSxXqgfddhvV5kiD4BXEdgGDAzpQUyY
            KjITKUB65kXUbsppJz4S6q0xtH+1e+vEZ2EBLaZq4xjUGKaQL/jLIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T18:56:06Z"
    mac: ENC[AES256_GCM,data:0nXuB5dXWh9SKedHoJgxPCIuYTEIb1TTjN1uOi91+n+vf8UT3QUG34MiZ4/3GMiYQbuzK5gVpfmZNZoXrb4+b/Wn5SV/YKFDBOn/0aza26a1XK+u9HVQGQLRObi8QR7t4ZF3M40gqCOs3Nfmef422ixtEBF7iz/kRu1NzN8mwao=,iv:IrCZfPaftpNWBCEBLAPF+m6yjmPeTG2Vum5bcEWUcf4=,tag:N4jnc0JgPY1AP9qVC5A0TQ==,type:str]
    version: 3.13.1
