apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: forgejo-db-backup
  namespace: source-control
spec:
  configuration:
    destinationPath: s3://forgejo-db-backup/
    endpointURL: http://scarif-depot.object-storage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: forgejo-db-backup-ssd-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: forgejo-db-backup-ssd-s3
        key: ACCESS_SECRET_KEY
      region:
        name: forgejo-db-backup-ssd-s3
        key: REGION
    wal:
      compression: gzip
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: forgejo-db-backup
  namespace: source-control
spec:
  clusterRef:
    name: scarif-depot
    namespace: object-storage
  globalAlias: forgejo-db-backup
  quotas:
    maxSize: 15Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: forgejo-db-backup-key
  namespace: source-control
spec:
  clusterRef:
    name: scarif-depot
    namespace: object-storage
  bucketPermissions:
    - bucketRef:
        name: forgejo-db-backup
      read: true
      write: true
  secretTemplate:
    name: forgejo-db-backup-ssd-s3
    accessKeyIdKey: ACCESS_KEY_ID
    secretAccessKeyKey: ACCESS_SECRET_KEY
    regionKey: REGION
