apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-credentials
    namespace: source-control
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:g/1/0hkSww==,iv:BghqNEHHJzSTTeu5foXWxzM/v8z2kKPd+kn2YAlqFbE=,tag:meDG10CHbK5nVBn8LbGFtw==,type:str]
    password: ENC[AES256_GCM,data:T0I6S5SKuoBotahN+3yrt2UbHN3WZWAZifeAPIbVJcc=,iv:EhuS35FMISTZfNt5ZVUpdCmuN4AIRjXhqc7xi706mLM=,tag:5Huuwlo17hUzH61vEImCGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNktMUzhLQm56UUQ5NmRW
            eFhiNFN3ejBLTXZwVnZldGRsV3Q1UFhMVFRnClF2bnh6eFZKSjBmRzNYNmR6NEsw
            UFUrNkc3R0J3d2ozenFHcTltc0VnRUkKLS0tIFhBMU5iMEVMN2JLRnRFM0xrSzRU
            bnRZRktWYkQ5T25ZeWxocytjbDJISncKhAu8j7IIPavkp8xwxOAXAtGHF558Mkyz
            /Y6lNkP4xPg/ehIQ33F/C+/HXjXb+99jUWzKxRGZ8oujAVlP+oJFbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK2orT0Fld05iTlkxbk8z
            MEpzM3hzSDU5NEF1SFdDa0psaXJHdktsUFdJCllHei9LZnAvTTcvVEZJZk9scUEz
            bDl5dHNmUDJ6LzlVYUZMdlpvM3VrMkkKLS0tIHJZS2tvZEY2UzBsdG9XU0JpVzRF
            emd6QmlhVGJSQmFHVFFocXJYdTZOVTgKlwbvMmryGwMcJP12uCnpQtQNGcC9uFpR
            5PczYWaTw7AOYANdJp0c7jV5Hh7sdPXMlu40o6qLsznpohFGyv22Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T14:54:20Z"
    mac: ENC[AES256_GCM,data:4EWvKQwxE1c+6DzOlQnQps89bbXN8Z5HMo8eQ6176lsl8G3sgjho2gxdpxgAec1AtFGIAPTaPZU8tjVJb3CLA+fPiSXk/00CvEeaPmLJn5EDz5mIsOSEsbYVS+tC3u8yuzGyF78QrwwoYmGw3pl+PzCEGIQdDuh11QrXRmCuQq8=,iv:X8/659q9hB+sR3Yj5FYGaCkM18eVDntL96dLWexB3c4=,tag:Zm3WxJA6fhC5mUa9uc6ujQ==,type:str]
    version: 3.13.1
