apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: forgejo-domains
  namespace: source-control
spec:
  endpoints:
  - dnsName: git.titusio.net
    recordTTL: 60
    recordType: A
    targets:
    - 204.168.137.124

