apiVersion: v1
kind: Secret
metadata:
    name: forgejo-pocketid-secret
    namespace: source-control
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:UOCcYPOO5jjv8vgRQXv8YmtC9stRtTsGeCSKhV1v7SKw0DA2,iv:KJLtAlFsOjYCucPdz2O38XoKjTQXxhijy888u9N3or4=,tag:eGEQIvxNLMJEoaCoU5xKJw==,type:str]
    secret: ENC[AES256_GCM,data:JIco67Ayym/y52X9bTsxgNG2tTStS4sLPmKy2eVFRIU=,iv:k7Y2yJGFFQ4DTMEQYskSkLkcwgplJvyxyGUJsuIVPn8=,tag:h3lUGdD1iq2hzMGTQJwtNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb0sxcW10b1ppZW04NFZa
            bE84OUMvZnd0cVVQM3VLazVzcXdOOWpsMWdRCk0xVWJ0NTZubUpjcStKNTNFTHZX
            UXRWT2pwOUwzT2VrQ1NSUnhuN3pUNkEKLS0tIEdaRFRHOGdnN085ZVBuVXY0ZWRI
            OVExRFZ6L0dqNWFFRFFsRlNwNUMwa0kKX98Cx3+v3cJGCx9qSiG2Ksp0qEH9BiRw
            XjhAWof+fB4mwg/aT30uGicrDHI5NAZe3EPn5wynvKnBWszBRHesQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlKzB2M0ZOL3c0L04wTzdG
            MVNrR2xTWjE2c3R2QXBwdUlmeDA3TW9Ra1dNCktMc2o4WkszKzRGbmUwNGF0SkJh
            NkJualhMMGpnT3JUZ0l3eGFXdS9MYTAKLS0tIHpzNC80UnMxV3NJTFZkcy9GSzE4
            QjQzUlVpUTRZMTJkeEtvTDd4NFdnQ0UKO2q7OZxoplS12fCDpHCXYVWrM47Z9DUt
            eso6JUzddooi5VKgWq8JF8j9r+Rye1u7uS6+hivx0RqZfl+eaxxtpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T18:48:47Z"
    mac: ENC[AES256_GCM,data:YwI+ccAvZps/KggAV8P9HkMFNABRabnjFYrqvdCswWXs8sHwA/h58Nu91Lg4OD6kZn8JISLWc40ORyP0M5I9IP4DP99NPYGu57FYaF+JqvDP7mubYhnmKCaZc/JcD8bgWMK0xNt/euNuJysTpVIgwuHNrnwq5p8Wi+wLImW3meo=,iv:nJ5LRDaPD0X87csuxdIMgWynh0ag18I+eOnqaui5IWI=,tag:DHde1n8gVqvC4jVJUsjThg==,type:str]
    version: 3.13.1
