apiVersion: v1
kind: Secret
metadata:
    name: custom-forgejo-gpg-key
    namespace: source-control
type: Opaque
stringData:
    publicKey: ENC[AES256_GCM,data:vX5SiIJv4lRyOW0zmY+F9DFKXP8oOnwURJvU/8/anSEB1TkYLTv0P7t4D2MH3lKm+tLC9cocJ4p+fsI7foxuSr1V6vXqMcmlUYWyzcCK9GN3gz48Il/J+F/DSTh2sNYc5cIWtHRQ0C+W9zntYwYzAc+9sPaXqXZP9INpBcIv56hiO5y0J6ORyNG6ptdfOGoZrQUb3RziV7bv+G9fF3qe1b+X2077175vVJu99SBmanpbBydQXm3jevigBkCzDuZesRk1AL9fhUi5LrVQyIN1Tm4y3cZcvoDquc2CgdwLzPHVdAYIu3XlGAlVia16Tf00lxU5dKRSd/Y/rBuH5i7LkK5u5oWVQ4lLrpIvZyHJ84BxYcoaLZeplrlrpfdhQ0Bl2f9GT9fYMjkJG1OYk+AzGF3UpvQv1F5KVUpnw1Hwj5dIHy2psMgTh/RD7WGgxCOVqJpVhNsSxHdX0mDvugEcdEeM2KguHn6Q/cJ25r6iiDyc0JF9YiiRuhsT58e9q86E8on34FbwqA==,iv:ihiSiPfqm/Ccj3HR7asne4Q9lEqoSHHQ1w4HffqRjmU=,tag:EgCyjO3POguMrJWQw8fdwg==,type:str]
    privateKey: ENC[AES256_GCM,data:L3AyOA59ULd3NHSV36swwVJ/PJuHgM79oDxLq6XhmcKeBHhLULWJ6hpAo0uO27zvpVc5DpJB/pgmAL0cSZOMoGg0VRXWj5KI0qBgjdQ5BbJDeO3PiJ0HuxFy1INv+riu+IrjhOnMKN+bPzyssdUd/DqQ/l20rk2z98n0kZLI8h1JhJphppug7+QLLoFraAqdKcb5smywJbfzUz8/DvRUk43t5HT/vMfjL/y8Szm5KA2kltBWHdlpUDIEzx+ztjHjf4EWdLsciMRes0bHPGoengg430yLesEBL7a6WA4A0AGKpCsdhiwYamw/YqBLyrgV1LY0y4cfwIQu9a2hZlwWoeowZTSMYU9Z1696huKh5Ybsia9Ebf/W3I9MUZS9AJn5MfhrnJ1v9U50DllypPiyuYmgbvxDUiiH2cB8ZdTo292jhPN0H4deYt6QYqoBDGAiA6IeNO6pI/iRXSLzxFR7K8FUJlqV9qvT1VGVqUgQmjELUmsPXgk0cY2AgNXOj1hwIRpgF1AxdFf8b13isXpBaC7j+3M/l2wl3aW+S4p/r51jYohotyt2RYejcYNgX0kK/nhihySmWlsz1Q==,iv:97wSHI6Aq4/FeIdtWFQNmuOKJDpCZIsJEugsrdnrAxI=,tag:Y1cq/gqyMWXBWxavbbIaOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSUFkcGR2ckR0WGdPV0FP
            a25KWUJkQml4VVNyVzN3YzdXUFlSY29HYkhrCnlFaXFSbFZYQ2JjTHM2amV2TmlL
            OXFnMk4vYjNSOHNFSTdXOUNBNUd1UjQKLS0tIFRXM0J4NnlBcFcxbFhvUmxqK3hO
            RitrdnljTUUyRzNyV09DMXVkcXczbGsKbuHttmh39FkKZU9SfA4OsXWw/zO4QEjw
            krB9tlRtBqDNDmAdvoMOAXC4SkHAgRiLR5NGwuPsU56WRyQ80XtHfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QTBDMzc0TlpzLzVxdFFq
            QU5rVnFVbG1PNEx4M2llNSsvUVA1MHhiSUZvClIvdFJONlFkR1k3cnpmaERyZ0li
            OGRidUVNbUNBdlFseFNZOGtGMk9ETDQKLS0tIGM1ZmJvaHNJeGJkQXIwa2ZpZlIz
            WEIvazlMN1BuakxKTFMyaVlaVDVhS00Kn3iziYw3pHTm2E8cEjP0/BejJgi8vIx1
            pDKYgXeOw4Gheiqz9dezbEDacVBQWX+Q5oL4dXhyts5dE2K0e36kGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T18:47:11Z"
    mac: ENC[AES256_GCM,data:/mvJKWsvMj5seUBMwDWvOc0XOlnKc1eI56WUFlAp19mmULHFcYqCoAMfgm4eQZX0pBQiOOhm4vVLzurEXaFIy/+8MfYwMAWK1J5X6L/xtCKUkUbR+BDEC5t2KU0FRF503NBPFx+c3Su0Us3BWVdfdD6IUT/tPVy+QNN2Mz9X+EY=,iv:fz/x0Fz5m1UW33+O/qLujp6wQUHxe6PdEyqNXsvl6Wc=,tag:zrdRVvHWnBFakjyVsuUn6g==,type:str]
    version: 3.13.1
