apiVersion: v1
kind: Secret
metadata:
    name: forgejo-valkey-credentials
    namespace: source-control
type: Opaque
stringData:
    default-password: ENC[AES256_GCM,data:bRqkMDKikY8lRRp48qN1Kt/lOfFZ+3uslilT5rxqJsw=,iv:AfFhcxCKlNkLFq1TVDfgEFoxHs4pkW5mxhPRgCFIB6A=,tag:mxLw+ecz2+70yoTPWkpWHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbkpSQVFCVlhGaFF6MTBD
            SlBPU1VSOXJma1JJZVc4UG5XcFlqMDdaZHdJCjVHbWllb1p1WGg1RHdzaFdmMDE5
            YVgveVMzaVIxWVRPRjZ4SDlqSHhXOXMKLS0tIFV4MFYySWhwZ3VNS2w4MnNMUjBo
            NGdVNDhZUkxRcjlzYncvdTNCZWtXeVEKojb7fmhYHxPiRbkuDH7F8iiLHQL7ogb8
            s+JIU8GD4/IPOVRljim2wHbMcnGE8uV6yEK0zQx4VXRKxM+s/ZK48A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T2Y2RGpsNkZGVEo2NU5z
            TGJydmI2aWdSNnJKWEVUbFBkZVNjVVJLTkFNCkkvN3dlMlo0Q3kvTGRKeGlzWDlV
            VmNhamVXZGh6cEFIcUpXQlpFQUNyZkEKLS0tIFBGTEZlQmFIYmFZU1ZEWlZKZ2dH
            ZVp3RjlGRGV4ZE1zYnZmNlk4TW9RWkUKBDHOnauYXyBmTtfSj0pajG2X/nDqzPkK
            2kXzHUWe/nidThf2WZn79xCEcpIMh4MCD0xd6mdrz2R+apEfngoRBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T15:24:18Z"
    mac: ENC[AES256_GCM,data:PRbNcwbD60kwU4EQEw8ovJX78meHMGOA158gD3MIT9DbArVlUcbVuRlvE4VgzHX0Jgp7WZcEVsgYGoEghrehD37pB2AdBlj8+OabMpVWsDM2AUf1J6PqQwvD3gbZ6UYB9FJgDFaYeG8c2rlY5X6lEGYphQyrjRtUfan0+qt3r0w=,iv:W+uSTKZYS4lqYm0B5mJwG0GmC2hlXRfV+FIqJ8UiRFk=,tag:IQy+gMt/bgsAIeiycXz8Ig==,type:str]
    version: 3.13.1
