apiVersion: v1
kind: Secret
metadata:
    name: forgejo-valkey-config
    namespace: source-control
stringData:
    cache: ENC[AES256_GCM,data:bqO3wFPFp9nvEgZP/Oo73+LgfotFNm85bljuvMWr7t4vkwP3NiCbkUV1QAQVJAQi7Kc40ek7rarM1M0+ejE8rRxF1iMioKFMXcgo60eKvHDuQBM=,iv:qoJliZwjSMtNE0lLhIRwtdAEeoq9VpUKKf0eRKvA/xU=,tag:1YlhNfc1LfZXvF7AVGq3hg==,type:str]
    session: ENC[AES256_GCM,data:fxvx53Z9MklrBDLL+j/jbqtemqJgm1fHY9dBT0CeLhm82JkPZB341KOG3tTp1obKVboC6DaQ+NkXbaa6ldm33Z/SYAwc35Ft+jdVYnNIfu4R0UzLG/IOqSphIxy5cpY=,iv:bKxbs1qVIr6qS9gYuKLRX13oZLlS4uFUMGbFPpAkIJo=,tag:szJjlHPlF4a/+tMwxESlKA==,type:str]
    queue: ENC[AES256_GCM,data:5JioDnLtMtJaFJbLVVUjU1/2Sd+LuhIWsDxrsMyMHfaQR1EubkdpOqkoIy5VlbajlCztHkDWEpnc+QTj9T2ltqQWthdM6gzvcdzgtR6XstlPLZby,iv:CL7/vYbVZKmd1PC2d60Fz2bjpz+s0ZqsX7bKirRRjuA=,tag:tvPGIBEiH0ToayUJ+d+oBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM2FLT1BMbEZxdk9tRnpl
            cnA4Y2E4QlByb0gwT3doUXpHU2x0L2dpK0ZBCjJoNlhnWURiUmcrYWJJQk9VS0Fs
            TkdsSDFZTXZwMXdXa0w1Y3BESmhPME0KLS0tICtkTmxVT1QwM2plZDJzRU1xSEd4
            S2FJSHgzdjV6eGliZEFVZHg0SEQ5bEkKgxlRUYvKpvTMPNmwcmkqCtqKYrkNTje0
            0JWC/dNnneugSOLcO27spUUeeDc670jTrAZdsIw3G46uac+/eN7lbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUzFqZ3B5Mk4ydWE1VTRl
            bm1UWVJLa2JxVGFTK0N1OVZaaHk2V1Q3RUZRCmNBNUw3NHUxQ0tYbElOeVR1UW0z
            dGloZVZyUUVXbkZ1dXREbExyb3hiZDAKLS0tIDF4aHFPMVgwM3ZUQmRIb0JaMjVI
            S1dPS3Z2dTBGRFhKUUJoVzJYdXIzU28KnntrsJY2KDdoVBdU+E6mmKQc5b3N4sfm
            P2Dw3hsvUGvJuEK/Me7PxHMkxoB4qR6ua/iXTeJFsBXYg8lrBOyoOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T18:59:17Z"
    mac: ENC[AES256_GCM,data:yKbD98A9Z5pTHhJ0pNir8cqOUgm9j/Zk2DIUQG59t+TGGW7RiC51Y4MROsrRY3PdQiMF3N2e+1BOKeptnGV3zcr/3vF8hkIsOL20QimFNGFsHR12yzIlqMjdpX/L5EuQm6/RMuUa/vHx9JMp/cD5OXPsaBBRqtiij//BTdjDWek=,iv:UM7dNFqiioTB5FTKfKgX483Hts5T4CQHAf8W57rQsTg=,tag:5YVNojtAiyoNo+N4eURjlQ==,type:str]
    version: 3.13.1
