apiVersion: v1
kind: Secret
metadata:
    name: admin-secret
    namespace: object-storage
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:AecrMWvYO11WEUnigLEBCaidCjVXBuRUNwDoJYadqgjcT7FiNRZHG2dB4XKtMHJWc0eq7Av+3pE/V80JFuX0Fg==,iv:s+OV9USvHGZ8XoFS7cs0tCloSN6S0qx+AtPe3/38jWA=,tag:dTjSShuJPOj4Sx7zAeUCcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMll4V3FsZzNVLzJYNDc3
            QWt1Q2YxT0RoVE01MTNteHdPbUlOa29lK3c4ClVJbUdFc2IzZ1kvbjdkZ3Bvd1N2
            UnhKS2hnN2JOek03MFBGS2tNM3l2QTQKLS0tIFR4bmlnVmV1akR0QXZmRE96SnBw
            VXBnV2xjOWtZaThWeVNRWWdDa0pIVFkKE9aLNEygFWaQ3joFu7LeVscGBFBwvIWJ
            gdfvW8E8se98ydDM19R5Bww5Ir8gSZtpiMuM9BllfLVFqiIkh4Mr5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibEtVS25LZHRjV0llMHRQ
            VVRoV1Q5a2cwWDhqZ2xTdEZBMnFWVHVqQlJRCmdrSU5LaGVDQjVPdHdDM3VkTzlJ
            UUtRd3ZJZ0lCSVprZnU1QzNtdHNzeDQKLS0tIFRSdUw2ZllTZTlZK1ovc2ltR3Rk
            Z3RPQ3J2Sk13TGl2MTBiUUpFakUwZWsK6ieVhCm+lgUWl2R66UQXqRS2eekmgExN
            rdPKxGzIHUzVM/eMKXJA93elXk87L/EChUy6ydnPro06NFKcKXSsHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T19:00:11Z"
    mac: ENC[AES256_GCM,data:8nHRwn/e6SEMpSc4UaZMnO4gbk22TWawgKLGBNMF+fCYLb9Ups8ZM+j8oIo2T4f4lBMv3ZgLxFcqYCOLmsIqByaoYHX7lb8sSMq6vaGZDIVJ9YLYgd/GqzvmXCIO4HaMttM4qJ018pp6gNXAbLoKjYn2/7kid3n3M1cyPBitMtk=,iv:3jv5xxYp0i1NCfUbMgcyTUXFTEqnzJAKct8K88KKdhY=,tag:rVpIwqa2GTtIyKrsfMA/8A==,type:str]
    version: 3.13.0
