apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: allow-access
  namespace: object-storage
spec:
  from:
    - kind: GarageKey
      namespace: monitoring
    - kind: GarageBucket
      namespace: monitoring
    - kind: GarageKey
      namespace: cloud
    - kind: GarageBucket
      namespace: cloud
  to:
    - kind: GarageCluster
      name: the-works
