apiVersion: v1
kind: Secret
metadata:
    name: searxng-secrets
    namespace: productivity
type: Opaque
stringData:
    SEARXNG_VALKEY_URL: ENC[AES256_GCM,data:tqOqJqe3hwmduA2rjr6rpt46wq31G4kFLObwFh6sJKYnU+WEvUSCjFv1xhduKsM7fqzRcb4pxCd0napIaiNkivHTKDM13nAP5IKIGmhWmuPRKWXRQDnEoYC41B0/cKdL3IRba9i2SyFqSzadvSwd2cO/FC8=,iv:k1hWeAP95sP+kD1etiH921BDTQUIAasDXYo82wJ1DHM=,tag:nTXGa7lToT+zEAoi4OkuUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTTAzRi9hWXpFSWphSmx3
            Z3plZ1hzMjlzMGRhYXM2V0VjM3lhYjBNVG5zCmoxb3ZieU5pRkJjZDk4M0Y2T2p4
            U0V4Q2haa3F0bksrdVRjVU9OdHFSVWsKLS0tIFFRUnhUTGt2azZOY2huVEdXSGVI
            SjdDYkJUUjEvRm9QSjJXQXhDU0V0aXcKguk3528NUeaFWEmVJJRZsuPfua/UPVt4
            HIAkRl+W2zrIpnxkfx3t6pNN/bD1ug0XZhCRZpOxxkdY5h5V+fWc8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5THA2WldLdnI2V1dZTytl
            OTVqck5KRXNFa0txREQ0MXFqWDYvWEhmWFFnCjdpUTVUR1NMSmVXU1NhQzllZVRz
            cS9NNHhSWU51M2V0bmxXZkwrZUJ0bU0KLS0tIHBBSTQrZWliNjNYa21EZ2tpa2NG
            aVFjYWhTZXNBdXNhcXZvOUJsaXZBNVEK23gnAimk2QYyvE8trlFu7KJ3PNqldB9u
            5CMwThdUmIpdB6zo/ukAWTiQ/B1eRKnawGNRQZ3jn3Yfi8swTEp5gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T11:30:41Z"
    mac: ENC[AES256_GCM,data:OtTYYIdwJX004XYA4SfqsAUWeKVXLmEzDQHbjN2o9vjOrUST5VZA7wAzO/bcP8h6sK686JCST3cFcA03OekrzNsE6+rV+wsxu2ATg2lBLB5XZfwWYucFossufyjf4QgSP+MAmTSotygIKYnVPkM8DU8DHAsD1IE5wVhsqHhulH8=,iv:2JeBixekore9hRLVFHTuQA9RFtvCAzDH6vpcwIviWU0=,tag:U7dsLm7sI/CYFo6tuAm+5Q==,type:str]
    version: 3.13.1
