apiVersion: v1
kind: Secret
metadata:
    name: open-webui-valkey
    namespace: ai
type: Opaque
stringData:
    default-password: ENC[AES256_GCM,data:gDpSqq2j9UkdNByBunZm/7aAQOsSDWl6MihdlZxoVkBXXkKvbILScSrC72bCFm3GE85J21g07n95MOnvwPxJHw==,iv:8mXvxwN4zmoHc7zhCJRKjdgqxFn+DRGnU9x9ZsSJ4cY=,tag:a+c4JnVo7xLjFufkZUJs0A==,type:str]
    redis-url: ENC[AES256_GCM,data:VTt50xYNXv4CSxwR6yLVJgiLPi1ZwYhSxN2dWsbAr8Ufg6nDfrJfau3JUGDwc4wF28NyxrH4+HddpHVqDBrJrDU2+cuVX4aTGLGqAzgHC5E8Ei+qhSrQovvNdaYfqG1KOLk=,iv:u9IxPNWlNzTYJJGS9lFSGVxfxXjwPUKyDfkD3xNFTa4=,tag:kIEvBFwXso+CUUVAF4whIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QlpUNTZodG5aVUt6WVdv
            MkFDMXBVZ2RocEtjWWlnZ0xsdGtLNW5QWjFRClFoK0UzOEpaMUtMRG9salVPVW1k
            Mm5Da0p5M1N6NjJJZ2lrWE1EekJZaW8KLS0tIG9qMGxDc3lJZ2RPcStSaEZscE8r
            NHBpRklZNjd6QTFLNlRHVXo1NE9Sd3MKXovWcIWkAT1Nwmpb1gE+x/Hx8UaaCdUV
            HNJG7m0d0UaOG6Ic025zmALBwhoFtJlcpo2Xbpu3yzK/tsvzNs92DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTVlZblRROTNpM3J2UGE2
            eUJFM2RHMkpuQkZyZHVPR052c3VuTnFpMWc4Cm8wTkhuRDRWcUxqbDM0WkUyeHor
            NkNmUTVlODVNWXpzYmFhMXhYSWloR28KLS0tIHJxUnJmVTVGc1hGdk9IQStGZmc2
            VTFkZGdqMkE1aE9IaFZVUFlSZG14dWsK+N6MWoeRzB/9X2V8qLR1rAsJdylTz6oD
            ZGuNfBBro2TxUtg4tqqknGLA1/ZEVBCMi/qbPOS+qY9dlOBb7L/o4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T11:19:27Z"
    mac: ENC[AES256_GCM,data:Hq8iXbc/X+NwRNIZyrQypCCBVg/P1b8hd6jjG7SQXcp38r9VWtzAZcXnM8TL5QGdu+AI0WFNJEo3f8LOVwNvMp8vr1XG2PWdz1iMf8mRmHSiDfEZGOOr1XkskBhTzyOg85XSLpsRZFXIZ4yZ1EebnAOYH0RIhq/j8Cf88LaIDtA=,iv:DaIKHQKzho3TUdL3P/mG20e62b4ZmqkepJGfPU6IM70=,tag:02VPD6QcEnuF53fEcgvraA==,type:str]
    version: 3.13.1
