apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sabnzbd
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: media
  values:
    secrets:
      - name: apiKey
        ref: sabnzbd-credentials
      - name: nzbKey
        ref: sabnzbd-credentials
      - name: newsreaderServerUsername
        ref: sabnzbd-credentials
      - name: newsreaderServerPassword
        ref: sabnzbd-credentials
    application:
      config:
        secrets: ['apiKey', 'nzbKey', 'newsreaderServerUsername', 'newsreaderServerPassword']
        contents: |
          [misc]
          language = en
          queue_limit = 20
          port = 8080
          api_key = $apiKey
          nzb_key = $nzbKey
          download_dir = /downloads/incomplete
          complete_dir = /downloads/complete
          host_whitelist = sabnzbd.tituslab.dev
          [servers]
          [[Eweka]]
          name = eweka
          displayname = Eweka
          host = news.eweka.nl
          port = 443
          username = $newsreaderServerUsername
          password = $newsreaderServerPassword
          connections = 50
          ssl = 1
          ssl_verify = 2
          enable = 1
          priority = 0
    deployment:
      container:
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
          - name: 'downloads'
            mountPath: '/downloads'
      volumes:
        config:
          persistentVolumeClaim:
            claimName: sabnzbd-config
        downloads:
          persistentVolumeClaim:
            claimName: downloads
    metrics:
      enabled: false
