apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sabnzbd
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: media
  values:
    secrets:
      - name: apiKey
        ref: sabnzbd-api-secret
    deployment:
      volumes:
        config:
          persistentVolumeClaim:
            claimName: sabnzbd-config
          downloads:
            persistentVolumeClaim:
              claimName: downloads
    metrics:
      enabled: false
