kind: Secret
apiVersion: v1
metadata:
    name: sabnzbd-credentials
    namespace: media
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:NZ6GJYaj7SseLoJBBo2gc+6MXEIbanN2KQ9yAVoEe247OgIQk/ueymVIi96LfP2flZ1Jq+FtzX3tV1mKvVm8UQ==,iv:CHg/8OPAMM9vhKDmRUdvvc1pxxqJtZTSqHbjq8e0SvI=,tag:aN/f603FbT5uAlWzJgrWqA==,type:str]
    nzbKey: ENC[AES256_GCM,data:TA5q8YPDNI7wQDhxZ6qiZc/NJSbIrOXGpfF1cAzDhtwbvTHTS5MGbuslC2gfVH+jO2HBgyLs4ssjuE/GytHzkg==,iv:6J8W7mLFBCOKFGa/wK8WpNnpJHL16bVFJfbpbHeohIQ=,tag:xaxz+LKCyHFstj4OLDS7Rg==,type:str]
    newsreaderServerUsername: ENC[AES256_GCM,data:W26H7knA8VUL0uP83si2cA==,iv:RwNZMmq03pSjN3YbUE9AHGnRBg5tR1PSvPQCWkM10ns=,tag:7ROsqF/BBUfPs2uFAirIpA==,type:str]
    newsreaderServerPassword: ENC[AES256_GCM,data:qdv88X+8ZASSwE2rsJA=,iv:aHRQx5sgCl8PHKvA3BWghl0Vd9gCXqTtGTh1Qtw6slM=,tag:cPidMNFvQzGO1CHhm7K4Qg==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVUVnTHE0eTBSRzcrMXFM
            eUxWV21Dc3J3ckZrSDI0UzhiODV4cndPMUc4ClR0cE9UZC84MzlDam14VEUrOHRF
            Y2pEMlNOMHBhckloYjNPY0JwM0piRTgKLS0tIFZraTF1ZHJIZzBwSFdrR240RlVk
            d0dJakVpVytENFZBTGFpckJqQmduUncKZnCjIE65LNrVIn8BVaSmApgDmkYYdxYw
            P1uQ/zLZtXpsvXMPyODcVMZ1aL/nmmU5kEzwyk4xOa7b1LfJuMUQQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcFlFaUVSSG4wOE94dzhs
            Uzd3L1VWUDNrVjRRdkhlZ3NIdjU5TjcwbEY0CklaZjZVdmlSczhHT2haK2VFN094
            MWYvWVpRcTFSeVF6OFVCM1VPQ0lQSk0KLS0tIC9MekpvdUxtSHpwb3JKQU5vS0d4
            dXFTMmRoK2lyWWtRV2R0N2JZbm1mNTAKuv5x7lzFZ4RHX8yGWkRdH4uYbV+o0QQk
            OTDO0OnkWfJNQqkHIJLL5XjxpFAq0Ok4JVIYyD5wJd35kTR4L0ykJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T14:34:44Z"
    mac: ENC[AES256_GCM,data:YPS6ylhxsf6pR/WGbTPSn95A090t0F3ulRCvQMSgsZSZ4eIBbiXD5UzMHcW+k+W86ItnOYUkg4BkaWM722lCkfNdSPN8ViilFC3moWG1kxQpZK6MoFakQUzbVNCrWPV/luMfDYNxQ/Jw8GjAWYp2HUlxpYB9TLriHYdiMbDKNus=,iv:h1WwCIST0nqVEZUu0gusFh3zj99BeiFdjyMpOXQ5VKM=,tag:1B1b06dmPgcCKiCdJPqJ4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
