apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: traefik
spec:
  secretName: monitoring-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - apprise.tituslab.dev
    - uptime.tituslab.dev
