apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-credentials
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:iYmyn6Hc3g==,iv:e6NxZ8aj+OtJeiUYtvBVcBy2X8RqhtnR3Tc78RPdMkA=,tag:DpyaDWw5QcGj3VC411LTuw==,type:str]
    password: ENC[AES256_GCM,data:hd/uCnyboQJR5/bXRDr6XwzRFEXwOtQuBok1t/Up5es=,iv:VZQMHEoBElT198nL4z68KqTOV7IDfK/Oo2NH497CWe4=,tag:GxgU+PphrGBMln4alfa1pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR3JkcVU3Q1JKZU53ZXZt
            M0FDcEN1d280YzhJVGYrTThtb0JkTlluUDNVCnBiRXYxbzZqMUoyZGtZK212cW8v
            M1FQUWwxWFRPbTI2S0RqZVo0VlVxRlkKLS0tIEUzYlVGTXRDT2t6a25UbEhXejk0
            QkFoQVBJQmNWWmo4MWtpVStRVk9NY0EK16GzXCvB7zVHo/kNqmyUr5xDxUjg/BJX
            tprk42tGz3geWiYSbyYTcfd7Cl/KRHjqXOZ8MFM1Fi8OVfMEQEumdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcHIzV3VkdTZqOGNlV3hD
            SjBoSnA0L3B5S3FmTFV6QTF4ejljbFQ4UVRRCmt3U25TS1ByUDhEaCsvSFByOE15
            elUyYy9IOUliSjBCWEg2dXROTU5aL1UKLS0tIDN4NFoxL25CWGhZMUFMcEZFa3Zw
            ckxhZDJsUDYydHNCeWlzUUUzK09UbzgK221LjfKxXQmSqMrIuC9be1AcTkqDbh4R
            Bjg09XRTsTqdknBhZsQjfmaJi3Ht5XlLMdJvjhLSNehzCPnEHRktIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T09:34:13Z"
    mac: ENC[AES256_GCM,data:NGwY06D9M0NefS6XLJchlnNj8QbuXUMOHl1oARMQUrNscDgBXzG34QfkPL9pKu9vWw4RpQVRuFUKBRXiDOEdlSyrj7as5bQcstfzh+tTPBDXGJaa6EX3KL5yyDVEBU4WUGaij5kT8qrCZcgNVNXzQIGvM/VzN+6n7acqOgTg7pA=,iv:O7AElMecQhd+iAbiS6A3nYv1U5wdmaLQf396zIF1sNM=,tag:4zoUannlIkhS5ZDlbWmXAw==,type:str]
    version: 3.13.1
