apiVersion: v1
kind: Secret
metadata:
    name: media-oidc-auth
    namespace: traefik
type: Opaque
stringData:
    pluginSecret: ENC[AES256_GCM,data:7CJ2iGPhJsL6tc1nguPm09E1sNk7xA99H5qXJIeOM24FsEi1Er6wKqC+0hdw1VkHOjQwEHxKiKroBAphLzNfkw==,iv:awLedcO2v/bvD/p+F2o/6OXQoY4onJGARS8DkEr02HQ=,tag:YoDP1C8OdSso8uRKP1shoA==,type:str]
    providerUrl: ENC[AES256_GCM,data:lS6INyeNrXQko3O7B/8tKyplUgkZ4A==,iv:sN98hTsJIUiEetcCEXWF6cy40HnHuoam3Rky6jy+NsM=,tag:B6UhVksvl3xxBTuWx6+o7Q==,type:str]
    clientId: ENC[AES256_GCM,data:7fR4fowkeQbhZWipLOlkkEUu251YE+id2dN4NqCMrRwXMRcs,iv:HR9mHfGX4Sinw6xdJCk0pHuxnlp0gJAsH4eCYmoGKso=,tag:Bggb7nNZ+WJqpt/cAwft8g==,type:str]
    clientSecret: ENC[AES256_GCM,data:0zqlQv9QJQ0q9jc5LLZ/OaaNanRuJZ0FUgau+It6Gi0=,iv:Q/o+VQnTpGhCdZExbnmVxi5MUOCVvEI/E4+PhyRaUIQ=,tag:O7hk/+AgjRwnIbcTahKQgg==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTmJwL0oyTUp4a3RZOHFN
            WTV1YTJMZzljYW5BZkpEaGc0QzFob3NXQUZNCmFNSmlQV1RRMGVnWktrTUJvMFRu
            alpuS3VoN05RbnA3N3pvNERhUGgwV28KLS0tIHNkbVYydVVtNW9PK09DbnhYaC83
            TFdzU3l5QnRqODh4TmxlWDdYR3lhdkkKQ0gO0oG+Bcn7fYmzt3zxC9ucrpr0RaOe
            YtcoQRzvsIoGvKZgCof7rYlrRXOFgw3jTRUv7rHTgN0y5FUpixvgYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU1JvTmUzNDJwaTRXbVo1
            NGhJZ0oxeTJucU1xYmZ5WnNFV3RzS05OYVRnCjB5ajJKYkQ2TytQVjhKMGlpV0pS
            TzFTeUJPTlBXRjBJOTd0S0VwNjVIc2MKLS0tIFlDN0dKTUhnZ1B5Ymc0U0VpYWE5
            RUc5Q3dqUnh4Q0t6OWlrOE5rdXRxQk0Kz9NO3xC8agKtzoMHIKAKNb8//nk3PcI+
            OMe0Yd7urrYcInZ9tBfs3JQa8z86kLsu8JBFJefVBayl/6jkGticAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T07:26:31Z"
    mac: ENC[AES256_GCM,data:dl1qYKKHpZVipnwl6Vq9kOpRnlHucsbMHIRN830d8SxH4j1WQQneCr538t9kgV5/qmd9M86K+ekIMD/ch5NeshGY08yqtyX5cecLUq0N1hrJx7MDVUGMYBdGpk2vne7y15Pd6QK0kGOr1sf+eU76HSTUmhgRir0drlTYlE8UJNs=,iv:cYr2kiCvPGm9aw9zHl4j1k0DfTaORlUJONKM70vwXtg=,tag:iUoY4zkZB5WJgAWbHIM+bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
