apiVersion: v1
kind: Secret
metadata:
    name: media-oidc-auth
    namespace: media
type: Opaque
stringData:
    pluginSecret: ENC[AES256_GCM,data:/p1zdCD5fJxk3HNUZKIlWx0BaFJrbY4/mfuPW778STg=,iv:8/PSHrJXwnRL26pJvqeVhxmYZuvdNqUe4RZ3XI89kyI=,tag:J6NnqEmvYjnIS5RCIAxV4A==,type:str]
    providerUrl: ENC[AES256_GCM,data:3gMf0OoZimJIQGibqEd1yTHRNuaS+g==,iv:w96L80RkM2Ykh3qdlkroKI9A5Pnl4jRvh4Flgrq2W8c=,tag:gQjG4kEU06HoXYEw04YSBg==,type:str]
    clientId: ENC[AES256_GCM,data:e8IiySKIUSJFtXM8ZgItU7HKoy0HpqP7KAJwMiRKcy1lYyTr,iv:+La7QSiRQ4X2fN6mWrtpO5JquAvKlqbkpKF1WGtY2bE=,tag:eFhxDJIHrYQ8a/8kqe/X1Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:JSyW6UZgTz3PmYkk2m3wPN9bqhARa9g2LUC8dXXpLZ8=,iv:Ny60cZ7OtaEapWufhLsGi4nq3jvU8fW2T8GvJZePCOg=,tag:5YaL2FTa3Q1r/2bt0IVj7w==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydis2OFErUnVqd1EwbDBp
            MDFRTUhGZE1TR2tkMStMbHhPYWdMaU5BWDBZCmoyampIV2hKcjFnKzh3cVdCSnBu
            SGhCOW84L2o1Q2MwWEZYazUwT04wVWcKLS0tIGM0bk5yZFFWOVNYZjVTdVp2c0JG
            akV6cjZKRXByZWNJeENyVkM4dzdMVDAKVxqDOEGg1VoSrIQabPdJsgkH9ri0/JT2
            mxNJAp5hB7+QX6YdKSM0msxzF6LFGhjMT58H+emQS8/5n0/eXyof+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdkFZQlc2a2lTb2s5MzdS
            WGdmSmZJRGw5ZkRReEFJaFVjSjI3SkNrTm53CnBObUZndHJTbnN0dDN0NnVNT2hk
            cHRNeXNXa1ExM2QzUDZxTWVGbjNoTGsKLS0tIEg4WTlwYndDampyMVdKWTBLTGhB
            WGlSdUVIWVRrQnVRUVFobjdCd2VZNWsKYNjq0OXZ0zkupYMWg3nd0rQNtsLb1atu
            ka//lGmZwtvScGyulWMFD/p9lEXSitqpWMOj7AycPw60H4wqHCKrNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T07:41:32Z"
    mac: ENC[AES256_GCM,data:mOe+4JTehx362l3CSPdlHmJvMrViyyYPM4FBbeS2qg4AmRbGEn0EuAQKI00gt7yIFUEbE1c5iSpwgbEW1FFx2X9TWmPHXPeMPWCKFzhiZf+epKa0QXD6adO9J0yzbi2HjBW17Uml/e51OABdDywvBLXnwDASW5z/iegMD7Jeh6g=,iv:vhcNUFdaiXd+aVgf4gtNa4hcluvBPZzD3enxALGwg5w=,tag:TOngIogDELvEGX8iPhhU6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
