apiVersion: v1
kind: Service
metadata:
  name: mealie-tailscale
  namespace: home
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mealie.tituslab.dev
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: mealie
  ports:
    - port: 9000
      targetPort: 9000
