apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karakeep-tls
  namespace: traefik
spec:
  secretName: karakeep-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - karakeep.tituslab.dev
