apiVersion: v1
kind: Secret
metadata:
    name: karakeep-oidc-secrets
    namespace: productivity
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:4J360tG2qYrvQsXCeSvXiLK1Z7VuzdtBYsKzA7Jrm3Eomo72,iv:p8/qGLQflSORDIGdw7SzHZsFuWlpvsT26o3NMruhtNc=,tag:ZkOAXWUQYNPKPqSJwmMGJw==,type:str]
    clientSecret: ENC[AES256_GCM,data:3gYjNBs9twHuXFx9XOb33n7LU/KLFg9nmNC/5/TjkUQ=,iv:tZYS3wptDB+Pk7kt2TduhfeY6Yo8BpWSVnnJpyIQkj8=,tag:sCwZpiei4/D4adNbos85Hw==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFN3c2xKZm50TWNQeDho
            YkFyNVN5eDh4SklqVnNKaVdYV3BTTTZuL1NZCkFibW5CODdSbytVaUdQUXBMUWZ1
            RDA0SnIyRld1L1Zwd0RRazR6U1hFV0UKLS0tIGtaL0JreHhuUUs0dXZjd3dKQkw5
            Nkg0ZUZKY1BZUEZqQXJDd0hCRzdIOHMK8Uhg1XWNmDzlMCc6e8iRr5YCI8pb3S1A
            1kcOqIScHJI+MOFrnHF6DmerLRNOZJYGg+Zz9U5dL87jRt6rkvacnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkJFRlRYTVl3RjBnUEJ5
            UG1Dd2dCTFNzNUQ5YjNzMy9FelhVL3J6N1VFClZpTkIrYVpoV1EyVHl6Qk13MEZ3
            aGozVTZLVlpHNU1FQkZQdnZ1T2Rnb2MKLS0tIHpFZnUrOUdMTzhEMVhkU0lSQi9m
            UzZYK0dKbnlWcDU4b1c4RDRQMEdoMHcKS6fWu9ZY0TmCgf3qSWlWTVm7khh13Mqv
            CJu9+5bJF419hIrSrg33pMZoyqOJRnf3+cutBP6wh3VVLgK25LgESw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:18:51Z"
    mac: ENC[AES256_GCM,data:dQJ5Yi+NhEP9cUBFo9SRlmaf+mtms1tpQJtFtP2HkdVxuiZucBBT5o2gvY1c0XaJsYPw8D0iLIvc8uLjllyngP7Wu45Wh3aXwPf5Pq/NNpnPhR04babdLPsNkt1/UmOnBGtItvWwNR9kxpUqKDNizlP6a2N5bZampGBsXxs+yRA=,iv:rLsw6dyKfeMRDyf06mXp0bpBT0h8j2gUYXuXsnFmbdU=,tag:tE2qbyNELw5dOaB7Mo2awQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
