apiVersion: v1
kind: Secret
metadata:
    name: wiredoor-config
    namespace: gateway
type: Opaque
stringData:
    WIREDOOR_URL: ENC[AES256_GCM,data:HIViAju0YmYxrGYRCmAJ7vlY+eGRAvstGi4c,iv:YJu2jaHkMC6yZa3NVnP8r93d+iWM+uqKVPJO30fK9hw=,tag:UOXAE5AUkN1D+Vuqk6AxsA==,type:str]
    TOKEN: ENC[AES256_GCM,data:BsixVIl9HLDlcVJO0e+3lYiO7QWHK7PJf900oYuWd5RJVs4r7sEr/GAfKJ0PmV1P+zk78CrNEz+WZRGlT5rIhsK1D16fJDtzuA25jguu3753sWSi7wb7xvRFk+WjV7+pfu4a,iv:+/AeP+XFzB/hf5Sn7C13nmOqEGUxIBYGFJqywYnRJQM=,tag:cIZ7PbbAtj++cxU7v/GeZw==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY2tSbVhvNVVNNmJxc0Ew
            SDBwS3h1NnZIVldiMk5SUDlud1FIYXZsazBZCkdHakFSWWlqMXBSU1JlQXRpOGVP
            dWRjd3UyUDFGTHowVGlScE9rT0lkMDAKLS0tIGhYaWN6S3U2UmdMVzRuOGRUek9w
            d2doYVBEZXVkcDFPYWdTNWhTcDV0VHMKPf8tf10tNFVWT1LliSxRGQXGGOu4vKAJ
            uXIRFW9c27Yk0zlrizAQ+cMXS72cD6ActEi1mRX/CVs4KjD4e0KCTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZk1sNTBxb1hiYnNYVDJX
            cWozNUNCY01ZTFR4Tlk3ZFAzenVRUUtqdENvCjFucEF5NDJJMlUrMTlOeWNGb3lj
            L2FJbGFGTVRydTJ0R0NjTHYwM2I4MUkKLS0tIERQL0dZWVdpYzhxSUo3VWd6MXIw
            dVlmaVNOMXRZWEVIUWdrLzl6VkZsZ00KodVBL1/9cw75SW5N1JbqK/I9AEUw309b
            yDkr1iTKa8CDp9wl4r0yYCcIkaUNJOuzVEWTwHCO2lBYsKzLJxdEMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T19:08:15Z"
    mac: ENC[AES256_GCM,data:gM6kPb9sAfv3+S9Kz/Xf9/1eeu8rs5CMfsTEFj5WksXQ3BDMDbtJJUY14A2BUVXRra5Oq6+Yaece1JxGEstP6EpWryQfHpDL59W7FahqYx8iAw5A8AfCMwkBK3+kvpWnwWqyaYYy0P2IfXbKiAPEH7dzB97nyKy8pgzrNxlRiaM=,iv:VZKkmqR1+fbbqmj3yNBeQCFyoBXFFt9nvwhb/3kiacc=,tag:S3T1tx6JxQJQz9qFHGjYWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
