apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: wiredoor
  namespace: gateway
spec:
  interval: 1h
  # wiredoor helm chart domain is dead as of 2026-05-14, so we use github pages instead
  url: https://raw.githubusercontent.com/wiredoor/charts/gh-pages
