kind: Secret
apiVersion: v1
metadata:
    name: prowlarr-api-secret
    namespace: media
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:phr32xB5xXhme5ATz0ApWqpQF7dq6bE4q1PQdfjlWiQD5uHlbWb+tygtA5ZaTc5V3bnMlssf8pMnMdXCKJlgbg==,iv:iSuT1pmH1qtU+ihNhDWc2yQwRTrdFLASavouJP3oj0s=,tag:ULsKWcPVLSH6uDyepi69yw==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydTdPcjF1RU14MUpBL0Jz
            TExOdGVHaisyZkdScmF2RmVPNkZXR3gzdzFNCjJlSmt1dlJBRmRoMHltNWdWdmts
            QSs3cENXcXkyTHYxQ2QvM3dRWEZWZVUKLS0tIEpCL0RLbVV0QjUrQ0FKc09QaTlE
            aGZnbXdNYmsxZmwvcWg1MEVJczY5VFkKGuPX3Q84pv78xMt9pVqgf1En9bQxFC9U
            2yuOkH0vIndrHj0pgNTU/r/bjuI2BDyf2NzCRduEFMV9GSjLgYL6GA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYVdrcjhtREFYZE8yd0I0
            bzdNU0tjd1NhUTJ6UWovWEh3eFVyUmJzTTMwCmpFdTZMRGV1anV0aExoYnQvZ2pk
            YVg0akdSelFwU0NlRzFNL2VlQTFJZzgKLS0tIGpxQjd6VG5TVDNDek81aVQ4TnND
            M3loam5PMzlVMnUrZUNwemtXcmFwcW8Ks6HJzJ+2waeKQGa+rfu2y0P/P5OO/OwY
            yCHmO8OX92uCO70mMdczMY8vR8/1fFwISvngtkRrW2YpjDoe5ND6/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T07:57:45Z"
    mac: ENC[AES256_GCM,data:ivvyzDmhfvxkjOin5BLQZvJ4xxwORAvVW1tPIwizwM9ViNf6eLF4u09pn9E/rzajIilZTZ4kt3M/IRU4mdMBGfiRYLi12yrrRTGz8f6SeV2GvS/zVQc1wHVyk9za/R2q0Kv4w5+YIk/Q2BrvpIIqtbrf+2en0GeX2GIMDl79wVM=,iv:Q3cZ/9jJnwb7DOBsQhXKFW1d1YpVwyCKCfX80hKbsLA=,tag:PA5mqArwXw5d5ByWxV4L5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
