apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 0.25.1
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: media
  values:
    secrets:
      - name: apiKey
        ref: radarr-api-secret
    deployment:
      container:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 512Mi
      volumes:
        config:
          persistentVolumeClaim:
            claimName: prowlarr-config
        
