apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: productivity
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.14.1
            env:
              # Database
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-db-app
                    key: uri
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-db-app
                    key: password

              # authentication
              NEXTAUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-secrets
                    key: nextauth-secret
              NEXTAUTH_URL: "https://links.tituslab.dev/api/v1/auth"

              # meilisearch
              MEILI_HOST: http://linkwarden-meilisearch.productivity.svc.cluster.local:7700

              # object storage
              SPACES_ENDPOINT: http://the-works.object-storage.svc.cluster.local:3900
              SPACES_REGION: garage
              SPACES_BUCKET_NAME: linkwarden
              SPACES_FORCE_PATH_STYLE: "true"
              SPACES_KEY:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-s3-key
                    key: access-key-id
              SPACES_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-s3-key
                    key: secret-access-key

              # Single Sign On
              NEXT_PUBLIC_AUTHENTIK_ENABLED: "true"
              AUTHENTIK_ISSUER: https://id.titusio.net
              AUTHENTIK_CUSTOM_NAME: Pocket ID
              AUTHENTIK_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-oidc-secret
                    key: oidc-client-id
              AUTHENTIK_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-oidc-secret
                    key: oidc-client-secret
            envFrom:
              - secretRef:
                  name: meilisearch-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    route:
      main:
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
        hostnames:
          - links.tituslab.dev
        rules:
          - backendRefs:
              - name: linkwarden
                port: 3000
