apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-oidc-secret
    namespace: productivity
stringData:
    oidc-client-id: ENC[AES256_GCM,data:vaVhs9x9/jAp0p0qdBpikB5cCFy1UNe1jHpkoLZ6LEFlC+XN,iv:smR0V5uUITfqOEkUnrY+Li4T3rlbKhh9EbG5l5cGHkA=,tag:mHdvKKg7bTmkIaw/b8dEvw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:Kt/cxSfGZfdbjMjlYyfXwP2K/Hr9shxiFFETivIx+AQ=,iv:vpV6okYuB4WxeN12a7n29VhQyvRBR1LTlgY1E3zLH1U=,tag:TiRnSz7EY5KzmjEToid80A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjck1PclphcytqRkdsTGIx
            NUZGRkQxZ3d5Z0p6WGxQeUw2TGgydmhPbWdnCmp5VFJiNmtKQmJtenQwUmtNUEpT
            dnZIRUJEZXlNNm52ZmQ2R2MyNndaeG8KLS0tIGtGTWtRWlFQa2V2cW1JTDZBR1JK
            VzN1YmFBUjNQVE52OU1GQlVrOXEvMzQKxCEerwfFl/HD4gbhVjfHIRqsQiV2rdhE
            67LjkppgnPU/cMNFtSdZmoDlD1+M6hWOas9AhNhv7VkNUhdqf5Woaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1LzVmSHlEN1F3YzFYcHpj
            dktrRW8yank1aUR2TzA0MVpqbjU2Z2xPSGtvCmZ4NzhvdUJtekY0RmhoWThFa1BE
            QTdPekdnd2JSb25nWGp0YkQrV1p6SlkKLS0tIFN5OENNaGhnYjlnN0JxbUdwd1Y5
            MFp1RlM0ZFBrVHF1NnJGMGsyL1JtL2cKPCn5+GyKcpRFxH4cx1zrEhExduAatgo8
            5DBHx5HYzNqnyxwOcqax0+XNi0cqkJOdQ1prjtZ/8GwfZl8OXML2AA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T14:24:45Z"
    mac: ENC[AES256_GCM,data:idHLwvkm+NFlLZVdggup/Uh8BXiFpdv60eyY6mk0mdkGGLHssmvmYoT+qYL+WdykS4EIQySyAu1/tjfqGl/4z/aBj2KvLnZ0O2ap1QZhyAC/ImOJdAxe4+zBpqKr2pG3hH5DJ0YIiLHUoQRHGqfdNR7b7IXu7p8vc+ExzJBSikc=,iv:VZJl545l4qizKJD5tSbIHp8Mw+1PlPoIO7oY+FdWrpY=,tag:U25dFDpGYuI6a3RWs9zoTg==,type:str]
    version: 3.13.1
