apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
    namespace: productivity
stringData:
    nextauth-secret: ENC[AES256_GCM,data:oiwkEUT5AuuIWU9D4nFWfdC0h1T20lHPu2Do1sm3XgU=,iv:T8PoeR5AqJhNFQzPQgcQYt04l1mPUsagjvWd0zbGxVs=,tag:YX9hN6qdNq5lmqUDgbQ/gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN0Z3QlMva3dMTy9pMTZp
            dVNJWWwvR1pVMUhJd0RlbS94QkZDMkgyMzE0CkxZU2Y4TmlXUVVVYTBtOTVCa3Nw
            aEdPdzUwQTBHd1ZUcXBuQ3RISWpRYVUKLS0tIFFPNDlWKytxcFdXaCs0M1hZc1NL
            YXhVb1ZHaEZSVUdOU3RkeUxEWlpMclEKtMZW0h656splFTY9kkDLK92B9mo3aW/v
            a3mqdpXMIXQTtffXOmfCOoSX40FP6HYq4WSiePGx6dVGYrfyYm/iMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMVVwWnU5S1VpTjVCSjVz
            NWRUd2FzeTE5Yks5LzN2Wmx1YzFwaVBKNGo4CnR1RUlsbmZsTHV5UlN0RlRwL3NZ
            ZGFJTHJjTmxUb3E4VzlNTnU5aEpCT1kKLS0tIDMzWkVocFZoRmxBcndDVkhYd0lH
            c0dFSm9OV1ZFc0ZCNDdmZzF0SlVqQnMKQX4wH4AP/v5Fz8Jj+FSA4bf9K+Gj77ij
            L+EW4ZLrke0e0UBRMBCAlR9vnYcmy34lkghwtYDB2QcqDFnPKy3HPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T14:13:34Z"
    mac: ENC[AES256_GCM,data:+y/lSMNgY8k5OmTSSiSyqm84XHNsqGNrCPq7HZ8uC1tSYeFVldyGNgnfzLOOU09dAbhH/ONE0iyXY+8mSyODCi6DOdAat2XuxbJQTW9n9zQ0jBRDZTVssbaiyGDzvf5zrw4X2bQ8rjU05QNaUlN5joFPCdhXnWDEOjRcfeMaNWc=,iv:aslB1/oBmx9YCjDQiEBKwY79p4ZwlhZthIpRLe4cZkI=,tag:eRbChvRz/UiOjBXzNVuxBw==,type:str]
    version: 3.13.1
