apiVersion: v1
kind: Secret
metadata:
    name: meilisearch-secrets
    namespace: productivity
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:3nRECSL2GW+WcCfNWL34UNwfQtW8Gz6BxIDPfxVauSPLYGkWDvvz1wNMtyOm9Wik,iv:PSD789HNK1W3BqRcYzJGHg0waICoCh+ujCfTMpny/3s=,tag:sSbOJGGA9gYf7ITXLF8waw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeW1qMkthbjlhMXdvWC92
            cWczeWpGTWxxcU5iRGFRby9heGNQZSt6T1JzClFNWEYzSTdlejAxOFBPdmhzVDk5
            TndZYU95cFB0QWJUUzVvL3BHdGhhbEEKLS0tIEhoZHhFdmord09mdkVUUmhSSURl
            UGQ4RFExRTJmK3RsQXBLQk5YVmk0VzgKBUfY2I9g0zMilwhtF/xOlXLp2HRc6knt
            t2dtnSU1f59YwsH/PnfHNeqp0zyL+LWfZ8OIxgKFl2uAhBQ1P3Tpzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK3l2cU1yek5BQkYzNGhZ
            ZEo1dWVFZUl0OCt5N0lCcGZnaDB0c3lmcndZCmg4ZTJhRlA1U00vZXlwaDJRV0gx
            QktQV3JsQm5kRGFRazA2QjhRSFl6WUEKLS0tIG5uK25UK3ZHaUxWd2kvQWlPSWhv
            RXhtOWYvY2dndVFETW9ybkxLRkZUVFkKqLO6nMnHKwC4Gtx25fu0YkUfFoTuTOX9
            FUhkUxyIdDSb5iVGj0ZZRzyEhoMiVyQEz34YQYlO5c/AHpbFEzKP5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T13:38:20Z"
    mac: ENC[AES256_GCM,data:fKH5AhAPTtqlqvN8k2MjvdOcBaue2YhFfnZ/LrH2aBCvJHHQDYiC5JC/SMTwqBh141PHEbQsG2XHMKZ7tPfEr0lfXE3WOgI/j2Dr/bzCBcTXMDjcvguf7EIY/rVIjsm7Bz3twDuxhJM/3TqGRK94Pxojbga818zlYrgSSVvQXhk=,iv:vjuVR5MwQ0Bt5gl94x5MDCaWxKscMh0tmAhOjt49Oq8=,tag:eDlQhp7tgDUUYHpYxJL9YA==,type:str]
    version: 3.13.1
