apiVersion: v1
kind: ConfigMap
metadata:
  name: apprise-config-template
  namespace: monitoring
data:
  uptime.yml: |
    urls:
      - matrixs://${MATRIX_TOKEN_UPTIME}@titusio.net/!VwFqlRnvLbETnPgWqI:titusio.net
  media.yml: |
    urls:
      - matrixs://${MATRIX_TOKEN_MEDIA}@titusio.net/!ajnjtkyKCrxmJRkUmI:titusio.net
