apiVersion: v1
kind: Secret
metadata:
    name: monitoring-oidc-auth
    namespace: monitoring
type: Opaque
stringData:
    pluginSecret: ENC[AES256_GCM,data:D1+J4h5BtEAtWJjbd6UoSRmd2aJ+KomYlIQP2WCyb6Y=,iv:m8Bio8vecthmYqbNQa8GrVVmZSTwQvbyi7zgpWVrZWk=,tag:SjFnVKbu5UARO61WN3Uz1g==,type:str]
    providerUrl: ENC[AES256_GCM,data:bHMmcsAbk8ITRaZ9xmgdARlLwvQY3A==,iv:i4/07lTVGNsDoWMp6/2euNeYQNF6HpzXTPe9zdBhoFc=,tag:P/uBHaJiBysLMnZq3diJlg==,type:str]
    clientId: ENC[AES256_GCM,data:ZRKBa8TBziPAw47BMfJtRmHvj2PM869kJjRVmG3XDygAChUx,iv:dsJgwfgCC8mzhQAIpGDgVzJZFZ/XA+xgkpXToh2+2x4=,tag:S5tIExIyfiwlpxZ21AZzSA==,type:str]
    clientSecret: ENC[AES256_GCM,data:oq4wpHtbHlBYMpkzB1H7L6mvhHbQb8Sri7s+SXWDdgs=,iv:+0HKIjq6FpRCGLsxuYUQX2z9cPtSQ8PocVM4Y9UQd50=,tag:c6EjMUrOpLvYn21TMBorEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArblVOejNnb1ZaSG1lbkNQ
            alZwS0ZUU0VkYzNxNFhEQ3Q3Mkd2YXU1UWtrCkszWi9QbmM5VUtpZHU5MmFKT2pD
            YTk2dVdnNGJBb015d1l4eFJuS3NNc0kKLS0tIEgyV01xMm5LMFNTYS9WZjNIWG5T
            S1ZQUEI5bUdlU0FkaURHSEdWc3JIbVkKkdDNakVNiuytAAmbIxNKSTUXpL7m1tQ3
            1qCFr3Z/dnZqYJg8BGindWCdVc7Z29WsLi3vxQnHpK0pLCuwTcW7Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNEZNL1R2ZHRacStvNS9p
            Uy9tWHZZZ2pCTjRvamZVeDVGaTh4NWVTOWdrCjh4QlRtajF5S3JRWm5vMjE5YUpl
            ays0d3NwQzd4WUw4TktzQW5wa2xwTmcKLS0tIFpGbXhLMG9ZMVpNSGdCNHc1dHJz
            anJ2RjZ6SlBDRkhMUy9iaTVqS3hoYzgKbqPqhtmLYQl9RldX6RGDf6ppwkwGZl9Q
            g/1BYvl0awRwlUydouyS/jo7hU5Z7Rcjkz6bqD1SrnAjFOJrA2OA6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T15:26:36Z"
    mac: ENC[AES256_GCM,data:nFJGpBlqatG49Np5sTRu4mGnLG2yUIeP60ZI8E5pfH9HH3N9GhJgpgjYAL+VpU3lPTHczOiy8A+qcYyTGvhIhhA/JcVSXBCoOOl8admJzl2X8Vfobf+IZw7S4Bm4BmNXOpJapz2L2f2Js2vfQp36XjxYvVmAM9ND4YoHBvDFU00=,iv:dPfFX4+UJrcmNMRLWxCm4DBABspm5u97Fny9b6EpbvQ=,tag:H7llYTsZ+JOt21JKToLrmw==,type:str]
    version: 3.13.0
