kind: Secret
apiVersion: v1
metadata:
    name: radarr-api-secret
    namespace: media
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:vz56aZgNixgoOMsb7VKO+FE4v0vUhe4jkLVBrBa4H5Ye3yF3wZ7hY2MMa3JQdozIwYFB+N7f+GpsL9l8iKRwPA==,iv:Y5nlVrB5dZrCleJBBb8RRjFN0LISlBuThnnw6UOASUM=,tag:XOJAK1QIlqbvnSKpO6BUEA==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RUMzdnozdkpOalNtRTRK
            MDAzdkdsQ3dnNkx0bXBhWVoyYlMyR1YwYVEwCkJtZjZBUUlFeTM1Mjk4Zm5HVEZj
            UFBZZTZlaDlpVW9pM0RQeTZjKytoMlkKLS0tIG5VMjhTQ1Zjc0RmemlWR2M4N3Nk
            c1BLRnBXMzlVRitkeG5BUjFXdnBKR28KcNXkc2r5oHxROB1xBwruUqL84nq0d2DY
            XjAn1NfZhntI4q/+6jz+9M32vdBAMewWERdh35a8yItqWL97qgvjZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNkJyZnEydEw2TnBUYy91
            M2hnY3RjcURScGVSRlhZeEVRblNJRlZMZXdnCnhHSmVUTFBCb3diVzRwSFYrUEVD
            VVVFQzdBNUFoRGVMajdoQjNwSHB4WncKLS0tIFFUSlcyRGpITzM3SE9jb3Y1M01N
            bjR3L0RDRTFzY20rT3JJTmZkRHJaa0EKVa/ALGzk6MwFuZDG9ZIzgMv7JHmrcwcG
            0osFH+fGkntNZuZI8mhZOngN4Fo8i1bXz9diqQWK4zif6JJvJ9GPEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T19:09:41Z"
    mac: ENC[AES256_GCM,data:4K/tgXOKiPsuRbzusDfG/9PvHuadOxrWOH9GmM+DYHHIvol7WX6Qcv5x/4DnG8dLygdeBHKGpCwW6l3DWx0I8xKrSJWXsK8WAnO7XR5WbZU06t7ndaIBOzS/eOOf3gGl0TMmAh9WW2AB549ykV/UO/EY29nAItT6LlFZZualy2U=,iv:bKlFsbQfJkesMe0fg6gzLiO2UIxchnImxU6VWhTJ1BE=,tag:mq6GkWmPl6RLPY8h+O2TEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
