apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 41.0.0  
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  # values are taken from https://doc.traefik.io/traefik/setup/kubernetes/
  values:
    deployment:
      replicas: 2

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    persistence:
      enabled: true
      accessMode: ReadWriteMany
     
    # Configure Network Ports and EntryPoints
    # EntryPoints are the network listeners for incoming traffic.
    ports:
      # Defines the HTTP entry point named 'web'
      web:
        port: 80
        nodePort: 30000
        # Instructs this entry point to redirect all traffic to the 'websecure' entry point
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true

      # Defines the HTTPS entry point named 'websecure'
      websecure:
        port: 443
        nodePort: 30001

      ssh:
        port: 22
        protocol: TCP

# Enables the dashboard in Secure Mode
    api:
      dashboard: true
      insecure: false

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.tituslab.dev`)
        entryPoints:
          - websecure
        middlewares:
          - name: dashboard-auth

    # Creates a BasicAuth Middleware and Secret for the Dashboard Security
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: dashboard-auth
        spec:
          basicAuth:
            secret: dashboard-auth-secret

    # We will route with Gateway API instead.
    ingressClass:
      enabled: false

    # Enable Gateway API Provider & Disables the KubernetesIngress provider
    # Providers tell Traefik where to find routing configuration.
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true

    ## Gateway Listeners
    gateway:
      listeners:
        web:           # HTTP listener that matches entryPoint `web`
          port: 80
          protocol: HTTP
          namespacePolicy:
            from: All

        ssh:
          port: 22
          protocol: TCP
          namespacePolicy:
            from: All

        websecure:         # HTTPS listener that matches entryPoint `websecure`
          port: 443
          protocol: HTTPS  # TLS terminates inside Traefik
          namespacePolicy:
            from: All
          mode: Terminate
          certificateRefs:
            - kind: Secret
              name: traefik-tls
              group: ""
            - kind: Secret
              name: pihole-tls
              group: ""
            - kind: Secret
              name: longhorn-tls
              group: ""
            - kind: Secret
              name: titusio-tls
              group: ""
            - kind: Secret
              name: mealie-tls
              group: ""
            - kind: Secret
              name: media-tls
              group: ""
            - kind: Secret
              name: monitoring-tls
              group: ""
            - kind: Secret
              name: alderaan-tls
              group: ""
            - kind: Secret
              name: photos-tls
              group: ""
            - kind: Secret
              name: productivity-tls
              group: ""
            - kind: Secret
              name: git-tls
              group: ""
            - kind: Secret
              name: nas-tls
              group: ""
            - kind: Secret
              name: garage-tls
              group: ""
            - kind: Secret
              name: networking-tls
              group: ""
            - kind: Secret
              name: litellm-tls
              group: ""


    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.tituslab.dev
        external-dns.alpha.kubernetes.io/ttl: "60"
      spec:
        loadBalancerIP: "10.0.40.101"

    # Enable Observability
    log:
      level: INFO
    accessLog:
      enabled: true

    # Enables Prometheus for Metrics
    metrics:
      prometheus:
        enabled: true
    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.20.0"
