apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless-tls
  namespace: traefik
spec:
  secretName: paperless-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - paperless.tituslab.dev
