apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-credentials
    namespace: productivity
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4UsIEFuJ437C,iv:nNaiwYWLPjXksStImv9hLFfr0VrpOVEkEMaiJT8JF7o=,tag:OZla3fVjylzBixhVWmYU6w==,type:str]
    password: ENC[AES256_GCM,data:viU7IVRBIYH8knfOEjViSW/msN6Zqj2+jhgWnG7SOeVP0/aPGwu/GAmB0lU=,iv:2JKRs9TL0XA5I4HeZY1F/l5pJBQ4tM/qA6dONbxVd58=,tag:hKVWgSEwsjenuRV01zPx5Q==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWFBtSWZhdGN6U0dXd0Rq
            S204aklrTTJJSGl0dXZKaXB3dldHamJwbjJrCjFXbVZINlhzWHZwWThwT0NtOVVv
            enhIRy80bzhOREdESkVHK3JVbERFTlkKLS0tIEtTRm40dTFFc2tYd2hveUtaZkhr
            elpoVVRVejNYMmpkRUhFS1FzQUJKRlEKH+mP9uDBqw5PffCGwtfiwuoZZ4JgkkAW
            NIYQG9e2fbYl5zA2mKl+jmvs5pusXzFFNW4I5M1tfS4iR7/iyrprTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYko4Q1lGRWpmZWJVSnBo
            S3JLL3RFNGN2NkRVcXU4VExtTlQzUk5QZWh3Clpzbm5KeFA1Rkh2aEVpOXFEenFM
            VHc5cEt5blpmU3FZTG5PN2tFOHpnM3cKLS0tIDBENUZEdVBpRlJCOTRSdEc2N3Zv
            dUZ3M0g0aWE2Mnk3WGtuR3c0Q0FxQ2MKPcG1nQOd1JP5LYl146xh6awEF2Ez4qY5
            nANaLVpBupi4fuptjJnDpmbeBRLJrzhhjVjAtlFAKVZoGAyNmIGW8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T04:54:39Z"
    mac: ENC[AES256_GCM,data:rkLPJSN4vsOVRx7K2yHq3VfQl7JfIo8aGLeWLdGX4KPMFY4Fu7hDbW8fNxWH8AY6rJd/eygpayN2/3OWsxsGjMvzmEN6K0TnxzQPymsSkhCfoiddB8yT6I5cQ3XUJxW/mij+n0ohNQRzM39cTaDQI7S1g0U5U7qS0ndWLyokQYg=,iv:c4VNU1UynFPWJyUZk+WtWghGPBWVjFhaYQxIzcNC5AE=,tag:8D3Ash4+21tjpTW4pg7kng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
