apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-database
  namespace: productivity
spec:
  instances: 3
  storage:
    size: 3Gi
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-credentials
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-database-backup
