apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: paperless
  namespace: productivity
spec:
  type: oci
  interval: 1m0s
  url: oci://codeberg.org/wrenix/helm-charts/paperless-ngx
