apiVersion: v1
kind: Secret
metadata:
    name: paperless-valkey-credentials
    namespace: productivity
type: Opaque
stringData:
    redisUrl: ENC[AES256_GCM,data:Szd96yTY362XMdCnX90tqPnNPQXgewPkUT803SuC2s5zYmVkMzloh4L4UU05t3NqB5dJ/M/KEzjkU5N6zJ2Aawzp8slbcqSnb7X+aT2aCvD1i5PP4Pw/4jHWehNkuvYAfLuoomBB1WA=,iv:MqY1m1QOHWSGTP3SBvlQJARbL+DY+i0sbyY46f32u9Q=,tag:pOE3HJnODeEoCoPkawI8yQ==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ0RZUWpJU1FUMWNERjR4
            T1IxOUFwVldkWkJDK241WUJwWno1Z25OSTFrCnNBZU1SMCtUVjBtYVZUZXNTVHNw
            MDhLTG5rZVB3TzVqN2k2OEJhRE1zWVkKLS0tIE9RNmxhRTlCSldaeTRKZU5Kc0RC
            WVZnSEVrOXpJRkJnakZKMDdNcGZQNEkKEzv4UhZTPQkUMH0CUJEA3kEGkHi+eSvy
            hMFfOXVU41c9FaW+4wBEMba4v+PCxeUNqALdE24MFijuy7Emu2Gxcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkdralZIL2RZMlhtK3VH
            d0VLVzVIM1JaVXVRVGNVUlcxVFpzTGtPVUE4CnBCNllBWTgydUFsSjI2d0lRNXUv
            V1gwbDF4MmloSHZuQm9YbjZ2bUFXaTgKLS0tIGVVeDJ2cEE0RW1Lb2hsRitDRW96
            bXFTMXJka2tRME5nRzlJV2tqbVZKUVUK5blTTchilj8tqvjaCAqUuBRtWdBitWlv
            zW8tr4qS0N1+7xhMg82BrnB9CAa8TFM7sJHjLK+429hLG/UC5007Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T05:08:36Z"
    mac: ENC[AES256_GCM,data:Wec4blumWwBDf7Hn68oMrOMrjjHbgsD9qYsx10BfiuU6XI+kxja70Py+3qUUShtftrOCTT/5K4JRVoHnxca6NDjWiYMpibB2yEQuUb0QiJ+M8HxxKLaFNMde33jby5MoUxizWOCg1mi3V5IXbG8VMxH8ikxmbOYq7Uq/NkEdl64=,iv:mnET0rO4NkCZ2ljV1x7pvnNVkitJW5/PzMh2Zp1Ds7I=,tag:hzZMY49A+B8UwuyF3RcTFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
