apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:yShosVto+CkBZsocB1WTdr0=,iv:CyJY7OTAQ8u60LPbL2PULI5MrqkwDcZvu7UynnRH4Es=,tag:XrLkBq7QQqC5ZUfYABUwnQ==,type:str]
    client_secret: ENC[AES256_GCM,data:+ehwhJBpXffU70BvW77BiEmAbDfXAlsLaCG2vIOJxtCdJVM4rmNJ2YLrUayuZA96Ve8L9wpnxTHRlVUntHaxog==,iv:4ShGPdeU68f7WsXZpZXHNJkLtUn1f9ZOxbSxAA/s7VE=,tag:3sK0ROTlgJ9Rz2TNrIkzMA==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWFRGK1RwYU9ueWNkRUEx
            c3dIYUt6UmZKQUZxRkVEZzl6RWZBWGU5RlVzCjhnTFZiNGZwZ2s5SFkxMThHSnht
            cnlmMXVwcG92WjEwSzZXTlZ0MU81U2MKLS0tIEpKYVhoTUpzdk1aMkNwSm9LMTg1
            cGFHSlJKRWNNV2tmM2hwWVlkODZvRmMKmpUMT5V7Zs5aZpUO22xR0H+gSAYb1qIB
            Ginq2ZHeQQ32aioJXmwtGsoLKbeleWKAyUJiBNqi2I3Nrp5M4hm2zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL1BqOW1tTnFkY1Bia2x1
            bXY5MDBGbUtrYi9mVUlXNGxtSDdFZ2JwcUc4CjVTUHZkV3Z1RVVoNjBLZlFTMmRY
            U2Z6YkhJSUtkTC94bFgyN1lzbHJKdFUKLS0tIHZwdm5meTd1MjdSUSthR2t1dEtt
            cEIyYytjMFhCVGk1UHZ5U0MxMCtmQTQKvGsLK+olkn7/DNgY4fFCWZhwwXICtxv1
            Szml3zANF5n/1AxGsKqlWx0bO5nJGvQN8hKx5qzqDbS4IdGB6lP85A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T14:19:03Z"
    mac: ENC[AES256_GCM,data:pqgX1l56Cy9XaSZ6KTZswuBxRX1sh09yMU0h2NMSZmVaFEyrlv57ImHELHFFHL5Vij8XduN77zxdIYKjNnifwaLB531BlFkxOgfNklgVR0JPnvvrUiohbbGkmxjEJnMP02B/ohDt8LKh2YRph7XhqRPQhb4XClKYS7hJwtRQZwA=,iv:LNM30QH/hrmXt/ewlKxey6FDMcAaU1U60KqhNknf3Oo=,tag:ongHeApVUvjFdMb91n+d8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
