apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - grafana-helmrepo.yaml
  - service-tailscale-monitoring.yaml
  - apprise/
  - gatus/
  - mimir/flux-kustomization.yaml
