apiVersion: v1
kind: Service
metadata:
  name: monitoring-tailscale
  namespace: traefik
  annotations:
    # add new monitoring service hostnames here as comma-separated values
    external-dns.alpha.kubernetes.io/hostname: uptime.tituslab.dev,apprise.tituslab.dev,grafana.tituslab.dev,prometheus.tituslab.dev,alertmanager.tituslab.dev
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 443
      targetPort: 443
