version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: avd4k6.61w039i0bewo93br
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBelRjaVAwcEprWFMzYnQrdXNhTk9JVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdOVEV3TVRBeU9EQTBXaGNOTXpZd05UQTNNVEF5T0RBMFdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQU14NnBUVG8wejhjeUhxQTRzbGRzcnFnS0pzUDFoeURmTFhrClp5MWVxVnBVbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRktDTTQwNm9PU2xITHNYcQozc3czaWtBUXZDQytNQVVHQXl0bGNBTkJBTHJUd3h5VjNqV0ExU1JKMk5OY2xrZmNIS2x3WmIvY2t0MDIzTE5ZCnNFbG1WQ2J1V1VHZTBXb0ViUFV0RWpLcXhhT0k5aDQvUXFQcnVlSkVpVlp1ZEFRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJQ255MHNxNEdwZ0RtaWk3NEdOeWJnVGJoT1hpa2tSWStZLzJkM0RrN1RXMAotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.35.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.12.6
        wipe: false
        grubUseUKICmdline: true
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: ZmeKOKphuU7UtNxYaQrEuLXpoYGG7ykkwE97sHshPv0=
    secret: YhiRR2cTJZOVgp0ECIOuEL0/6vOQtdw38301pCzKip8=
    allowSchedulingOnControlPlanes: true
    controlPlane:
        endpoint: https://cluster.tituslab.dev:6443
    clusterName: core-worlds
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: l7rm1v.bpox4f1vmu4d001g
    secretboxEncryptionSecret: OgXyNoMvFVyB9876vgCbJTIW0rNUcVpK1KB/3xRbcDs=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQU9PWG9PU05SOEx3WSs0YTJKSjc0OUV3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakExTVRBeE1ESTRNRFJhRncwek5qQTFNRGN4TURJNApNRFJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVE1cVNxRVNTMWRDN0tKSTQ5RHN3ZGRhc1BQQVBaU2h4dnBCWGJVekNtOFlhNnh0ckpzOXJ6d2h4TjUKeUdabXRTd21pZWZrMGFuRnlBQVdua1lWZG40Sm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTWZpcEYvSkhtQ09wZnVlUTB4MEU3OXI4cXBJTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSURtOXc5VWsKWVpyNlUwakpwSFJVVVdhUUw3M0ZpL2xjSStXSU5lS0JqVjZQQWlFQTFua05CMm9YSTNNYlNGUzVjUkZCcHo2WQp6YmdiWFZTM0Qxd3FpSjFNaEVNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZXNnlmU3JjRWNvNFFrcmhPVG5HdEc3L25jMDIxd2Z6VU42SkxZbXdQRmpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFT2FrcWhFa3RYUXV5aVNPUFE3TUhYV3JEendEMlVvY2I2UVYyMU13cHZHR3VzYmF5YlBhOAo4SWNUZWNobVpyVXNKb25uNU5HcHhjZ0FGcDVHRlhaK0NRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFhZ0F3SUJBZ0lSQU1zSGk1SFN1SVJ6MWd2MlBrcEk4RXN3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5qQTFNVEF4TURJNE1EUmFGdzB6TmpBMU1EY3hNREk0TURSYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVFhVDlqRkNTT2VXVFI3RWVGT1VOMXduUndsZW9TV3Bicmk2R2xLRVNnSk1OODJEeVpBClgwdTc2TTNBR3JtNWthRUdpanZxdFF6L0NPWlp2dE5UazljL28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGQXFvQ0xDUEJ4MU9jbytRZ2o3RUtjT1Y3YlVrTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDCklRQzVQdTBUL3crb2JnWnc5dnNoeHBURXJlM29IMHlxSzBJMkZOdnJBdlRXRFFJZ09NdHdjS0JzTlFvdTdzUkwKd2lhYVN5QS83SWJYM0x4TmF2YzM2b2htQmhFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhpK1FyelBoSjBqVE1CSi9iMHpuQU1LOUVyeEVFREU1c00weWM4THpTWGZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFR2svWXhRa2pubGswZXhIaFRsRGRjSjBjSlhxRWxxVzY0dWhwU2hFb0NURGZOZzhtUUY5TAp1K2pOd0JxNXVaR2hCb283NnJVTS93am1XYjdUVTVQWFB3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBMFgySjNQYm80UllLcURWZ3Rmb0tCTXVScXMrYVhockovVFRMZDh3OFQ5MDdncU8xCjNPb2V2Yk5qb0NtSUx4L0IyMXpsdlQ1YWI4R2V0YzRyRCsrMU12bDBVcFFaK2pzREhmejhESm83djY0ZW5YVWQKNHluWHNSZ1lrdFU5Q0owdEJObHI4UC9KQm8xcHlRckc2cUkxUExTa3Q1bWVoT2lpb2Zmb0Jndnd5R09UV0RiVAp5bjZqcklJZm1TbGlkV2xDWmIzbGV0TzRrbVVDWG9DaG4zWU5pWm5lZmVkR1dtbzI0bjRTcUI3dWpzd0JZRjV0CnBiMWRwazExUTAvVC95bHFYcjcwMkE4Yi94ZWJjTjVYTG0vTzhQcCtSOXRVSm0yZkl2dk44Q0R0MFhkVTZrY28KNFZlR1E1c3dYUy9raXVMOE43R3hodjN1WGRzU3NNZ3VpbytXNmtyWGV0dG1oNm0xQTVveGZ4akU5L3M0UTQ5WgovaGVra1ZydkF6SVBVWWxTWkMrSWt1LytKZFk3azBmVzR2WlFkY20vQ0pzN2ZteG8vVW9kbkhmY3E0d2pIRzlJCldWaUlnZGlEU3o5RDVvcUR5ckVoa2YvejRXaHhMdXNXTFJPMkI1a1Njd2EyOElEeXhFRE5oSGxGT2ZqemJlaDcKaWs0YmV4VFUzMm1MUTcyYUJkOGFMbGM3aFN3U2dDVVlTa2ZMRXhoSk1qT3NyU25GcCt4WTMyVFdDalJ6dkpragpweXI2TEY1YkgxZTJ6UkNkR0tBSWI0TTY1RkVadmZBZmVzMGRwQWhFZnBETWlqVkE4UUpOL255ZVY5WFFyaG5xCjRnWDlsejZRaEZMbFpQZDIvbkFBc1o4VTlEOHErcGx0TFd3dTFBdlQzRFBvS1dpbFpUQ2pOWjVXZGpVQ0F3RUEKQVFLQ0FnQllhMEVkOTBUUmcra1psL1hxdU04enVPd1JpVEFoV2ZNNUlPaGo5dHJaNW9sd21VSndMSXl2Q3FFWQovNDZRUFRvb0tTeDZWRy85VFY1OFk3ay9MN0J1QkdXNVdQTWg3M2hnVnQvWFBkM01DR1M1bHEzM3JEaHljYllsCmUwVVlkcWFDcm5YbHNVQWF1T01XVEtzcWF5NUhJZ09IenBuZWhRWG5rT2ZvYlcvQ1ZHempSYmpjZGRrRlBhS3kKbFlvTi9sQmMrdXA1amhVUURQd1VBUHkyZmpBMmpMQWd1ZFd5NGJPcW93V2kyZk5jWi9TSXhUSklTd1hVNUVxRApENVZ0MUFBbVh6aWVYTG8zVDdKMjBCRkI4MFVINXVJWDJCWExabWROYjdRN0R0cnhsd2xMSEorL2hKNlJ1RldRCmIxOXAwMllhNTdBRFJ2Z3R1d0pIaFNaSHExVkphRklzMGxpazEzMFRwZnVOSS96NVFJUjBxZDJSWWlvcEdGQ2wKZlhudGx0d2V1UmY0a3owZ01lMWFUYklyWVBVTC9Gb2VDQWhtelFvOHFOVFVURWVZUXBZQkpPV3ZINGtiUEFkZQozd1lxam1iRjdlMnAwQUViUTlqN0tyMHBvQ052dmlXYkt1eU5Gd0RVdEk5Y3U3dWQrU1VldkkzQUxWL1Y4Yy82ClYrVFBoaHR3em80UG0rd3NBVW5yS2tKdDhzRlh2OHZIc3EraW92NUloeUVvY2tBS1RqczA4MytaL1B1cFZkbm0KSGxIbC9hQ216b0pNbTVHWG9lVjdDR0I5OEpyajhjQW1leERuTUhhamE3a2wyK1VMVWZjaVVPZExMTlVUWWdkQworYlpZM2wzOWVtS0tCcG9YNlZpRGF0RzNUdzV0ZG9ldUoxVk1UbDUzbXhSNkpJNjhQUUtDQVFFQTJhaTFkbGVTCkVIZEsvVXNrSEh1VzZOV1crRFlWdzVwQmpra2xYbGFQTlhXb1JyYlVWbmkzdG1CYU9vTHV1aW5aOG5FVnQxNy8KVGd4L0JBYWFQMHY2bTQ2Q1IrOTc5STE3ZXlxcUk1bElkQ3FvV1MxTkZPTlI2RGJnVWFTVTI3LzZuUzFZaWpqZAptaE9UOUcrZGpkaGF5eE1jSjBMSEovcnJpUTlhNU1yUStxOWVDY2wrSVN1ZGRrblRNNUFIUWNpZjZlQlU3L1RJCkRkc3ZPY0o0ZVpoK3ZvbjVza3dTZ21GNUN3Q0ZiVnhNSUZtMVMzM3F5bC8vUHV1YXFjdldrcndZVWpnSWEwem0Kb3M3U2YzaWNKL244Q3RlOThyV3JGSDdseXcwOENpdVhqSkNSbDJVSTRjc1dHTHBWVmZ0WkNzSDRlemRlb0dTTgpiY3NycEpIRDJ0MkU3d0tDQVFFQTltUjNlMnhaVWFvVjZUdUNPS2ZFakZ2THplR0NzWUFramxzRHZrWXpoRjZ4Ci90YnVLd0I2dXFoNTMzdm9JenVQK1BrUEtaVnl1MEFKaGNKVmxwRjdhcjRvd1JUOU4xVXdORzhWS1RUQU80OGkKSzZVOEZUWllpVkt6N0xuQWNtZkI4dk9UUWdnbHpmTDRGdkprOFYwYXFhYUlaaFdLWlkwTE5wdk42VUkxSFg2bQowTFVjbjVIeVRYMjA1RTB2a1dVaFhkckpvOHBiQXNDbkthVkNsSktzN3Q2NlVON1hYeTQ0UnVCSjVUNmlYeVB0Ck12ajVoUzdjMjMzdks4QkRjSGZoeTFwRDc4VXlURCszMExWVU4yelllL0RJSys1MXl0RDUvOTNscWYzc0l5T0wKeUNTMkZXd0RmVmxUVElYQkZoQ2dzZDlDSkI0cmFtQk5CZzVxZlNlZkd3S0NBUUVBbEdxRjBmeEVqUlhLL0l5UQpReHZDKzJFcFlIY0F3REFmSTNhZEZJYlJnQktLZkMyTy9LZTBIWmYxN28vNVdOZlExWkJtem5Mb2c3L2huRTBrClFLVCtiYlB2QWo0NnQ3Y0J6Q3A3ZVdxOERQcEpjUVdDMmd0bmZvQnMxVDcwZ2lPV01EY0xlTFR0NW5JVElVbzYKbE01Q210YWRDK2h0Qk1ZRWRhRVN5WS9Da0Mya1llZ1RLV3NrSTlTVFAwV21yU1N3WmptaHNUMm9iRXBaR1htUgp6TmcvRkkzZ3hjTTVtODM3UzVVL1ppTFpoZldsdWFSU3hVeFFNQWRYbnhCdmIvN3lWcDMrbjZ3QVdHUFBCVHlvCnZsbW5rMzBvK0tjSDBTSDJiMDdHOGVobm5tRzE1Ulh2eUlkQ3VmblUxcHhkU3dpWTl1djZpa1FHYkNkdHl2bmEKSXhPSjRRS0NBUUE3K0NING9WdHYrL1RQU3BPY1ZJRUxKSUNMUUpyOXR0R3U4RW9OOHFveFNwY0tEcWZ6UVcrZApwTW5jOGh5RERza3c4UFdXeW5BZFVTM0FKNWVMU1NkL3lIN0UxK1gxcEw5UjA4T1R2dW9XMVBTZEtOOWh6bE5vClFQL1gyeklTNWx3WFZOOS9qOW9ic1VwZTAycHNNSnYvdEsrNElRQUpUWFh3T2FXNVkwcm9QZDQrS0FhcWMreEUKbmhiOEJpbFF1d3VPKzJSZWdDNzhrWVZlSm9INUJXWWYwWWdKak9OZ29EQkVWK3pFWmlWQkFNNkh2SCtHd2V3eApaQXBsWEt0TllYQk1mVkRSdCs1UkRxVWZvREs2TnJ6T0ZjR3lwNXgxMjcwdFlJVzRoVHdISld5dEx2bytab2JHCjZJblVzeTFXd0g5TUs2bStmclZVYzlIcmFuRFN1MlVIQW9JQkFDZVBaOHM5OEw1ZmJCOUFVc0F1SVVVem5DeUYKaGtsVlppYzc0YWZHRE9aOUM4QmYvSWt5REF1dUpuNENFSmV1WUxYTFhuN09qOUhsT3FQUjNqS3lpTElUWFF3MQpEWXphdWNCY25wMWNPR1VCZGRtcnhiK2prZUtzSlRKN3hBZldGd0Q5Ym8zQjh4WGZ6am1vbzhzdzZ2THAvc2V4CkxZUTF6bG53TVZSTGFIQ0s5NWNzZzU5U291WVVsdjN6QXpFb3JhdWR6V215bVNXNjBVOG53TEx5MlhhUUNJY1oKeWNQSVBzVEZKaXpwUFR3bWVGOTFoMVg0VDJxaU9heDFlbkRQa1N1WlhTcXJKaVVKL1Raa1JJTFEyOWRFT1V6ZwovQTMwT1NiQU11dDF6WDl2NkFxK1pma1VzV3JleGJrb1Y0N2xGaldINHZXbnBMbXJYdWh4MWd1T2NPOD0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.35.2
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.35.2
    proxy:
        disabled: true
        image: registry.k8s.io/kube-proxy:v1.35.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.35.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNPZ0F3SUJBZ0lRYjlyTEVWVVBoZmdNK0FrVE5TbXBqVEFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURVeE1ERXdNamd3TkZvWERUTTJNRFV3TnpFd01qZ3dORm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkUyS2M2blRVSXZICnRtTW5OTDZoSFRHa2xFUjdJZmpPSGs1WVhvVFNBS0VYeTdUaDgxMXdGMi9OT0xHTktoNDRpaVE3TEFxT005dFMKK0tOZk9NWUxiVmlqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVRThvaEcwM2V3b2ptCk5MRGlINGdSNjBLRnBOSXdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSlZyLzJUWC9XV3JyMXp4WFhuNzJZVmMKVUptajQrSmVoZjQrdFkxZndVSnpBaUVBa1pCM0hyVnBtZmUvelVZVlRZVGJaWGszTjZiaFQyRTVFc0FqS3orVQpOY1E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUprLzRxb244VXVJU1g1anlGaDRFd3Y4UjJpRXQ3ZVNQbFNjOEc1d1hWZ3dvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVFlwenFkTlFpOGUyWXljMHZxRWRNYVNVUkhzaCtNNGVUbGhlaE5JQW9SZkx0T0h6WFhBWApiODA0c1kwcUhqaUtKRHNzQ280ejIxTDRvMTg0eGd0dFdBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
