clusterName: core-worlds
talosVersion: v1.12.6
# Image includes: siderolabs/iscsi-tools, siderolabs/tailscale, siderolabs/util-linux-tools
endpoint: https://cluster.tituslab.dev:6443
secretsFile: talsecret.sops.yaml

allowSchedulingOnControlPlanes: true

controlPlane:
  patches:
    - "@./cert-sans-patch.yaml"
    - "@./tailscale-extension-patch.yaml"

nodes:
  - hostname: corellia
    ipAddress: 10.0.40.11
    controlPlane: true
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/3fd91d15e6d15abdbdfccc77644f6a023dcd4d52d356947038ce7efcdbd60505
  - hostname: chandrila
    ipAddress: 10.0.40.12
    controlPlane: true
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/3fd91d15e6d15abdbdfccc77644f6a023dcd4d52d356947038ce7efcdbd60505
  - hostname: kuat
    ipAddress: 10.0.40.13
    controlPlane: true
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/3fd91d15e6d15abdbdfccc77644f6a023dcd4d52d356947038ce7efcdbd60505
