apiVersion: v1
kind: Secret
metadata:
    name: plik-db-credentials
    namespace: cloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:EZbLBw==,iv:LJK0NWMeYyqHtYXo7vgICEE4NQMpaWJAXmwQwewMNlk=,tag:3vR1tPDKrOjboCmn0JVfxQ==,type:str]
    password: ENC[AES256_GCM,data:md4VukCd7hEmw37bOfY7IsFwWYitRHvoYQ4Stb/X5lp26zCX84DerPsRs2WwwslW,iv:uBC8VrGNSTL9V3d3EitSfj5xhx0gSWjRnVOeQ36Onkg=,tag:qKPTgoehS3LmPRdfE2CUKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NGhqcHRaREpnZGFwTE12
            eXFXZFhCdm1iSHBYVDdSMlpFK1g1bS9OeXprCkhDdnNNVEhWM1NLcEpHRXFuUFQ4
            VVd0T3ZrcHZZbnQrMmpNUlRjYXJBQzAKLS0tIDlBa3dvRWJUM1h5OXFXdFN1U21k
            d3lPY0IvaW9jdTY2UzF0cEJlMFZpS2cKPyy2Np5o5owZiassjyAJdKHJwKTdqW+H
            rMww0wvGK6gpT4SnkaHt5pA9avwG+jlf9/3PKW1XQ8sG0lTZpoPjiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNjBNYjBkQjZ1NFpIc3VG
            UUlYaEJUK3lOMlNOY3Z5bmtab24zNG5ubENFCm1YVjM1TUQ1MlJaVXFrcnpNaUsz
            MytUS2p5SUIwZEdYNjB6QUoxTFhjNncKLS0tIGRpeWhGbzdMdVU5RG9tR2t6WUpt
            K3ltcHpJWWhxakhOYnhJODZiWWxCbXMKxMOK5tKa5ln60OX17zZu2i+UUd3W1+99
            Su78Yg8tlFEYn+bKsmaMKhNRz+AwJPsjulj2r2Fb0X96LSKuVY351A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T16:42:59Z"
    mac: ENC[AES256_GCM,data:OLI7yjCMGf5BxypFT5o59HhsPKqMeGqg+QZ+gpcmyz2DLiRy6Ht26oDRcNuvrZbqAvy1PIs2ZkG0ZE+ZPH3Ue7rFQw16dwvv0s1ywH4Z+yoalir+smrUjyU28fjbC4EPNG8Nn7UQN770yyWGet1kK9ILsKhd3VM98fb6ydCGKPI=,iv:FVIqPxDCYWYqE4IT6a+SIAeKawjazjZCy5es5O0N1AM=,tag:R7ROCHe9r63HiN1NjYzW5w==,type:str]
    version: 3.13.1
