apiVersion: v1
kind: Secret
metadata:
    name: plik-oidc-secret
    namespace: cloud
type: Opaque
stringData:
    oidc-client-secret: ENC[AES256_GCM,data:UwhPQrJUE2q5Cuf2lpz4AXi8VYe5gXEtj4lCLS5rlj4=,iv:WmQUMHSgwQP42OOzdXuVkdLdkLcqLTZqJeIyu/YUulg=,tag:n2IRWDMgqVLH+KuAUn7N/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbFJFQUZBdCtTL0tnbGsv
            Tjc2R2lKM1NJZUZGVnhZS1RLVEdhK0tORUNZCkw4SHE2YUdkak00RE8wSVJCcXFZ
            bHZyaGFlUjlkUlBMZmNuREIrUmQzeGMKLS0tIGVIY0ZUUHJFWlpMQVkvd0szV0p6
            YzB5UkZna2RsbTFzZzkrMkpldEFrQ2cKgjtd2q5mhKLTyp50EVLSj0Utyt1KwT5o
            tqjZxQAwzmohxpGibr9WyJQro5W/DBJ7cw74R3zErgQLvyrOfyKUzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUnRzUmJTbUsrYnhvYVZy
            RmpKY3U2T1JlVzFHYUJYakJtV1BNeUFnK0gwCnFodkJaNG1RMnFIdlVnQnU2S3RD
            ajhLTXN3bkVxVzh4WS9Pb2gzUjhhdVkKLS0tIGYwZDVqMHJNZnMwNEN4TG5NcWxa
            ZTdib3E4WnJOQUY1S01iRjVWNk5jbDQKCnQGUXGA02RlUVtGk5HB1qUTVhd7Bdys
            aErOFj51Zxn4p5gruIGmZZ+P6zwke/ahVbDyBGXClpc12S6bkLy2tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T17:03:08Z"
    mac: ENC[AES256_GCM,data:eFRiQ0T/AwBpxRe+DNT/JqaAIuzvMv9rbGPHs29fkNwtH5g1Pe29NjFGh1Hq0fMIp9rQjGXCUzwjmyGnNx4J129lBQn+efJYrUj/06xYCrnQtZzd5MStAwH7U+HmSVv+f+mptuasqUxOua72BULJr2afFqN0qggKzdusdElLlTs=,iv:BvfADZvWKa413JJ+/UVyhvMF4I4kabLa0vAOZwNqQdI=,tag:6THLmUkuN/Zyn3i9qTCcDg==,type:str]
    version: 3.13.1
