apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: productivity-tls
  namespace: traefik
spec:
  secretName: productivity-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - search.tituslab.dev
    - searxng.tituslab.dev
    - searx.tituslab.dev
    - karakeep.tituslab.dev
    - changes.tituslab.dev
    - paperless.tituslab.dev
    # linkwarden
    - links.tituslab.dev
    - links.titushome.dev
