kind: Secret
apiVersion: v1
metadata:
    name: lidarr-api-secret
    namespace: media
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:Q/BaQcJ2142pYLJQPGHPLGzussmAsgJJcOm9YvHmTjeD3IZg+KsKeVi5QgBWjuRqVgm/rim4Z1E0bKppJB9qQg==,iv:j02LMP1zVVBAD7yknIgE1RYouyCLTDwNRd1f9/1mzm0=,tag:yrXkR6IZrAwkGJpRt4d2/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdTlSbEx2QVc0ZWtvN1d6
            U24yUTRGYVhtR1RKZlczMTJnWllkSWdyczNjCkduWVo5N0VQYW02NUVJS2xLanlD
            ZGpjdFE2NkY0d3FzWWx2WHMrZ3VGdzQKLS0tIHNScUt3RjBoUy9LK3hjaWduV2dt
            c0ZBTW5FVHduSWsvVlljTStJZTM0MEkKGRbvNe1fE3+ycA8jjFfM7ha2zjLHryk/
            vJfQcGaihTl+4CYLFbYkF+QRuxlasCwy677tgqtQI/bYqWyHAQMtpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cldFUkEvc0pBSDV6NXQ1
            Q21JcEJ4YTFtaUc4eExwNjRFQzQrUXM0TjEwCmVRN3NIcDVNRjhObGlsSUNzM0Z2
            dFlGcHNhQXVkYnFJSnFaMVZYS21LK2MKLS0tIDhrYkZ4eExaUHB3NURSdEY4ZVVX
            UmR6dEpZRzhwTlBwSG54aVRXYUZiaTQKoSAmQebPM5EsNVNT1cKBQ7qupQ0tKl7G
            uQ6O6Rd44eu05GrekuqCf2tZ5Vu1tJxV+U4o0LD5jtX5acRHli5wEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T16:55:48Z"
    mac: ENC[AES256_GCM,data:7EhUe1a05KACyxbV8oHbNZsjLL7tZLz/v6rqO/4aU/DFcZ5AW3Ckj2DIkEcVOAB3sMm1Oxdd8ACAxFB7HOn06A2pCq06YoGJ3V4wTEdA/YDXGn9dwPtLxy9C2hNvZci3v6PgIaW1KIKMLBtjH5mU3lBeqw4KJF3F6pyNPsPtRhM=,iv:rMZqMb2yV1x0PHdH0nTTbpQV2S3HUAv3q3xHaknkQog=,tag:Cs5g7HrOY4JFL0Fr6Vs22w==,type:str]
    version: 3.13.1
