apiVersion: v1
kind: ConfigMap
metadata:
  name: apprise-config-template
  namespace: monitoring
data:
  uptime.yml: |
    urls:
      - matrixs://${MATRIX_TOKEN_UPTIME}@titusio.net/!hteFKWOiWMdmJtyUsX:titusio.net
  media.yml: |
    urls:
      - matrixs://${MATRIX_TOKEN_MEDIA}@titusio.net/!fbSEwoaQdVaPePjujw:titusio.net
