apiVersion: v1
kind: Secret
metadata:
    name: apprise-matrix-tokens
    namespace: monitoring
type: Opaque
stringData:
    MATRIX_TOKEN_UPTIME: ENC[AES256_GCM,data:59SXY59vlGBU3f7eH7MEAssShueU4ZIs83pPtCVzDKTWzZnaBPb3Kow=,iv:i5XcUIsKEAWwWLRXSRQAbysdZsa4s+D4GK9ulxVrBro=,tag:XCnZVMXOBAPFN4jQ3ElSHQ==,type:str]
    MATRIX_TOKEN_MEDIA: ENC[AES256_GCM,data:NGvSHMH4of4=,iv:ZTy8cCLDuqry5/q3cW7MbTGN/dAME7+pWxTYuKJ5XKA=,tag:+OIq71mlC5frxhzCVP+9kA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOGV0ZjdwLzcrZElXVWZX
            OEMrTlhmUDUzT0JBcjBhbzJWbDdmNjk4NXprCmhCL3NsbzhpbzZLUm0ydUlLdmtQ
            QWFmWFNQMGF5bXNtY2JBeU5zUVVGbW8KLS0tIEIzbC9TbW4wMnlzZjUxNUhPYkhL
            TjBCYkpCNElkaHZ0bWM3S0ZUTklpaVUKocYe9nOSnr/iA16FM9CbZ6Po+JLcbJkq
            ur3Qux5LO3zT4EaAa2yndJOnK6Vg5x1m7rB7YK/gr+hghLgHXNfodA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Vy8vV2RWdUpTblRremlF
            ODZRU2pkTHliczF6OGl0NUduRlN4eThWQ244CjU4eThia29CYlVnV3lHSzk4N2tN
            ejFNTWpITFdwK3FrSVJGb29tc0VaUUEKLS0tIENhUDJMazY5MFd0UG41L1UyeTBu
            SFg2ODdsa0lua3hBZFZkeW1JU0pRSEEKM6P5MVDI/agUGRMOkj5KGzy1+nnsUwFs
            oxnYDcRd2gNOeWraDiy50uzNuawoXLn+QfvOqvLnn247qzW3PVrcyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T16:50:33Z"
    mac: ENC[AES256_GCM,data:xVvXAd0vkX5vER9Hd7TrfwKc4JIzK/3b3hduaTQ8W3AgVlm2hTyd1clziKkKQ2BLa2qfONcTVwXcnaMHIs+vWlxDSP9F3pYmD3zEGHWXl4acM+V1C27L5J2NouEiyV3XTz18HbbXV1eaVPaQpb0FYbweDzCttaOjiov4N7Tkv94=,iv:dxpg9N+RZ+X2Km2BILl1DHoIr1PmryRBsBBuz4vUf+I=,tag:nd14AguGAfhc+WDDQAN0pA==,type:str]
    version: 3.13.0
