kind: Secret
apiVersion: v1
metadata:
    name: sonarr-api-secret
    namespace: media
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:5t/dHwG/4XPO6qmFUQLIrUcYWXnPAiS9RsNoX70rNMLT4BvOTfqJNm5/8H8f2M8aA0PCWvrN7BLPPLwUaI7WSA==,iv:ARE+L15oC+cMNCoCv9FHz/3pNRdN4n4Mu21nF1aC4v4=,tag:vbE5aH5rLu4iCGDHcox9YQ==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqblRIM2xWVGthYWY5UzNS
            djRndXNGMlA4OUMvRm4vSFZHdk9FL0JEYkFJCnZvTnUvZnZUSlhsYWlnejUrVDc2
            WEhNcS9pLy9TNTVMR0IxaDRvdTUyYTQKLS0tIDFPSjJodnJnNWF4aDQvMmhYUnA3
            M3lLNW5WYXFpRFRkMHl0Yyt4eFVEcXcKtnyOrVcnl0QdHZde3J0ItgqJ9C7gBJS3
            iBVmYmond53vQTZ3jXdLS74ZWI+KcaZ5iSpWavzRld6Qs42qmsTsgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcVNicEhrbjdiOFlYNTF0
            bnBQeUZmamlDZlZVSWh5ZkxiN0hOVVVpUnhBCmNRY0NCb0hFN2ZHYmgrU2xCYUZr
            UUp5S1RmQ3BybDJIdmtUZjBzQUp5dVkKLS0tIDQ4dEZCNXgvTVlrQW1NQjdhUkhj
            d0t1Qjhwa3JRRXNHTUFWSXJHYmVPS1EKKbSODctON8dBcbkbf5YFtxZ4Z0Z8l14/
            wO0dIFPcxBpf7bCA9YPf2pD7ZddOaRCyDwKfC+QJ6A6Z3DVjaG8Q8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T07:08:31Z"
    mac: ENC[AES256_GCM,data:JgxVQk2zB0hzRUWvi1SY4kGjSzJShNFU7OecdPXNsMFsm9rfZa/VaCY7uT51S4TNt7hb3FKbhGC8SZjLhTRUyRe/tx1hZCm/9sdXQ/vtkUqkUGPFaalGeOHS4cUFTgWBOcOhWYTgBwZucml4B1xY57FXOYSBYtACdnQ+yTxLA1g=,iv:kZIr1ZV1KoYSJ1hHgPGfURkYUNF16UOORjIsHVOPYJQ=,tag:hEIilHAMNxIcN1iBV7dprQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
