apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: mesh-system
spec:
  acme:
    solvers:
      - dns01:
          webhook:
            solverName: hetzner
            groupName: acme.hetzner.com
            config:
              tokenSecretKeyRef:
                name: hetzner-api-key
                key: hetzner-api-key
