apiVersion: v1
kind: Secret
metadata:
    name: hetzner-api-key
    namespace: cert-manager
stringData:
    hetzner-api-key: ENC[AES256_GCM,data:EvJUEzz4t5ZWmogqnpApYarE+H7Cq1P9ZNwJoCuXR3Gi+NUIfcfaRVst3mzh58lIstQzwB5KeueBUy/ROtJYDw==,iv:SXZRxdwD7ICqUDh6jk1NDLy7tTJGQT/Gz86Y/RMKEKY=,tag:B+Ms75BMCEIlKozV9NUOsQ==,type:str]
sops:
    age:
        - recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdEhKb2dWWHczWUNIcmUr
            djg0SkVJcEdJZlo0Z1Z6Q0V4bTJrcTh5WEUwClEzSGtYNStiVy9RcU9WcllOREo4
            V0pPQTMwbm1pdTF6OGExRTZxNEt2Y2sKLS0tIHFMcm9BanNZUDdwRHUvQUxWSk95
            anM0R2JLZ0FRbjB0TndlVStURjd5T1UK0IcValGBb7frRclLCwKdODZHNBm62yJq
            HHN0QgMnFEgvP0Bbb3JxX7d51I5L43sjTjMpHIPXPb6p5w1pD9S+zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQUZDb2VzS0JyVHIrOHdz
            OEJjYWI0WU5Qa0dhQXlTZGY0dDBabGx0UnhFCmU0YWNqTUVRak9tYzZ5cDZNeG96
            Nk92aFFpei9hRTNvRzZzOVQvTTd6TEkKLS0tIHpCY2NIQm9ReDlBZ3ZSZ2ljUGdh
            UHZnOEp0aXkrNkswekx5MjRaSXh2QmsKnV3pMktnrNWvcyNQG1CMLBWgDM+QbP5P
            IIlHfe/n47bQ9BcAVcR5QqCU5PZCadVV4xKoU55j80GZ55xi/5giwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T18:01:22Z"
    mac: ENC[AES256_GCM,data:h/o00CEW0B0fe6oGJuHDWIOSxKaH6WVKX61OHa2QDqAgI4C0FMgApdkmVH+0poOEKwP7ilv0rxKBMVHVARAetWeZWOtAtkFfxkzjUCjON+iq4uoM/ijgI3tPDVjFSDpsppjZu/KUCdCb0fX+V45OlSiVlajYZCEcquUUUtTpAtc=,iv:4sX0nnEUbnEAcNqXJotxvURr/ioTMLGkzveCWq/CBA8=,tag:YyGqMBF8G+rIAMg1E7NT1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
