apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-credentials
    namespace: truenas-csi
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:sLNrlR22n34nc+eU58d0M88jtWFW5r1GFI4c9VVJKdwj3GqArVt5NpUxzglVRVXdIL5C834FjVwI7C5KfbvtM4dW,iv:7nr6AQuThzKLueVtHmMqjQiRKlHTSkbdTLGO+iDvTmc=,tag:oUOj6FDJnPVNCRmS0Stksw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZWM0dDhQSTR2dzdqZFdM
            SS82T3I2b0RJSFYrZ0RQMkdxaDc2QTl6UFI4CnhyQkJuUGhtZ2ZCQStTb2x0QzUw
            RDk1RFRTK0psdDluN2dWTXllck5jdkUKLS0tIGFRVlkzd0c2Rk41NUcxd2tuQ3d4
            NjM3RER2UEtFa21FNGhKd1VVZDRZdlkKOrl/Dvo3+FYdDxPdWtxLMGBUGkbZh/Rk
            sUxN/+F5x5LbPBykOth5nI7MwIoCwgLT18Y68megBTcuDwinL2oa2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL3RaSFpmc0ZYOG9BWi94
            TlRLVnVCbkJvR2lsNWFaNmZnemg4ZWNTSGp3CkNqNjh2eEZpUG4rWDZQSmJzaG9y
            TkdYaGdrR2dlT3J6Zk42aWU2YjI5UDQKLS0tIE9GZSs5YzVBVmtlRjVZSFY3VVVQ
            T3loNmc2ZmdVclhzdGlLWVBVRWdBNUEKpFKy87dq9YXBtY2piyxxGU2O6Yxg0Esa
            TOvJC5+BXbOpm/DW/Z3waVL36r/xVbTM3NhY7lGLNn3TATKu53xX5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T17:55:48Z"
    mac: ENC[AES256_GCM,data:HicpoWpDl2KPr/6RqmzxcxDj4doj03QIqM62uyyJYlv86wVERxivigR/y+OYOZPst2p4R9iMz+v9y0xcBC5OaHoryjYeE9L55+Y1uU0da8seA3t62p0IsCguPNG1tKlrRzW7mJpoZwVNHsOvHCE7LDYM1J76VBjK3PYSINX10AU=,iv:SY4mKKyznPp/CRxi2ZdnOlp72W2fa3eJWkWZEnck9Pc=,tag:fY5jU/cDTfXJZ67Q4Jmedg==,type:str]
    version: 3.13.1
