apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: audiobookshelf
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bdclark
        namespace: media
  values:
    env:
      TZ: "Europe/Berlin"
    extraVolumes:
      - name: audiobooks
        nfs:
          server: "10.0.10.10"
          path: "/export/media/audiobooks"
      - name: podcasts
        nfs:
          server: "10.0.10.10"
          path: "/export/media/podcasts"
    extraVolumeMounts:
      - name: audiobooks
        mountPath: /audiobooks
      - name: podcasts
        mountPath: /podcasts
