apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: deluan/navidrome
              tag: 0.63.2
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 4533
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  failureThreshold: 3
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /data
      music:
        type: nfs
        server: 10.0.10.10
        path: /mnt/media/audio/music
        globalMounts:
          - path: /music
            readOnly: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 4533
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/controller: "ignore"
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
        hostnames:
          - music.tituslab.dev
          - music.titushome.dev
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: navidrome
                port: 4533
