apiVersion: v1
kind: Pod
metadata:
  name: obsidian-cli-admin
  namespace: public
spec:
  containers:
    - name: obsidian-cli
      image: ghcr.io/titusio/obsidian-cli:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 256Mi
      volumeMounts:
        - name: home
          mountPath: /root
        - name: vault
          mountPath: /vault
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: obsidian-cli-home
    - name: vault
      persistentVolumeClaim:
        claimName: obsidian-cli-vault
  # restartPolicy: Never
