apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-cli-home
  namespace: public
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-cli-vault
  namespace: public
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
