apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synapse-db
  namespace: chats
spec:
  instances: 3
  storage:
    storageClass: longhorn-single
    size: 16Gi
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
      secret:
        name: synapse-db-credentials
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: synapse-db-backup
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mas-db
  namespace: chats
spec:
  instances: 3
  storage:
    storageClass: longhorn-single
    size: 10Gi
  bootstrap:
    initdb:
      database: mas
      owner: mas
      secret:
        name: mas-db-credentials
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: mas-db-backup
