apiVersion: v1
kind: Secret
metadata:
    name: mas-db-credentials
    namespace: chats
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Pta2,iv:sV4k2DlfL2j2Prm7HKP9aF/NWKlfmc0ymgDUOM2wf/E=,tag:26h92m+bsIiEg5FtHeMS1g==,type:str]
    password: ENC[AES256_GCM,data:LN3uOcRywt8QPIj7Tddd2XX79EZF1NhSDsDJav9fFIPbw6R/TrWMRHIx9OfNoHjikJVDvUEAhhvQfsTq+R7bzQ==,iv:BAmCRuXvwu+BXYVCRgr+gaKt9Aqpp84YH2uVBRspQzo=,tag:B4YqBVlqGkDU89ibqpWjYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R2RXcnRqL2ozQm1sL1py
            N1ZCcDNtM1VQd09UMG9DU0ZleVBqcitDSzAwCnhHVW05WUtWUnBoMnJ4QnIxMWFR
            RmpHbDVidzB2QUtSYit3VUJUUEliSWMKLS0tIGVhK2Q3dlF3dnlhUG5yaURHVXBw
            VGt1czIvRG05djNyc3NwN3BHSUNpYm8KBsBQMe9tRthaZPSnlkebgVA+ANX5oDAK
            JDC1pBmZn1R4rBKO03FhqnuxnkTNiOY10x4t30Oti8VbEZNxGa/BGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUERBU0wwRDBCZXMzV092
            THdoeVRmeUtDZXh3cWJGaDJNb2toNy9Wc2dVClNEL0ZyRit0VFJhWW9mOHRFbFNS
            cXlBVXlQSVVwODZiZ3E5dmNqK21BNEEKLS0tIDZzNjJ0a2FUZE1Lem1nM2JCdEVO
            UW9vRHlRcmZjeGFmdndSYm9ibHpJK1UKjRDqyGPSLLE9Cty331R9ox1LVYLVzeXZ
            6rljsyDPZaL6RkYoAZtmMlwwEgnqa0Y04UEs5r33r4Ui+x9i0uAlkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T12:59:11Z"
    mac: ENC[AES256_GCM,data:E/LQkpcld0rL1qBzhZAtHfWmRIy40bER+U9U2j7oNjvCSvMcDBXNkMiYpYd3bGNf0C3NAnlXVr7XqJoRCsAdNVRb81KZw31kXRbIq1fOp7cV7SWkc2ryLQaHgsdJE3O0brsoFf4QBX6948OA7mvEtpQXKX1cVK4/2nzJcPR9HWA=,iv:YIOvdV5kKxUgVfyJjRgJ4wnw0tT78osm2UmhdUBiNgs=,tag:Y4BhX8W2nHzbQushIbxYog==,type:str]
    version: 3.13.0
