apiVersion: v1
kind: Secret
metadata:
    name: mas-oidc-config
    namespace: chats
stringData:
    config.yaml: ENC[AES256_GCM,data:I2U4Xyx3obkjNCJDy2WDMsKNmFQfHcUwOYyQ0ozpCJJpgQpEBOdsZoietDgBTZ7Z1Ivkd9fYJuIhu4AqjPng6Xo1FB/i9h9purRVQVSq8xMUJeZ3mkdo9DUZSY+F+IZYiL+4pwDtIbAFyqmOw3WGnzwVWz3wwG//evBwr0bmeQoPRyZnDx7vGQ1WboVIB+o87NgFqktTad7GG4Jio3u9GNVq2VkuJOwwdmpNDpAnANZDkOtMJimTC6MJB4HdfJANJOKnNJhlVTlEkwyHRr87FWAezzmnAdXL240sEiUvdkDqAnaYf67l0s344DceR6MSCHOY2gr/9MgaItgsILkbX0FpuoFO1Zt1NVFZnScIM2bo43EZpINYQq8teRM6YBC/2o7Z7TZhkDY21IBhQHQfTF21SNuPd7N5nzVxqHcD1CGd/o5Ej46rKc72dlAEjtC3V3S5hpe/9D68UVHrlbIVXxHSr/F5DJ8vYP7UHqwrCf+73Wtg4SgE18cJJsGGaAxmYtTty+QM4R7r8//0pCa8E3JFCp8N1x95U/5fgC+UD0b6+7hAYoGfBVIAUsxYezZMLWjF5x/lcQXkG/thaEFxwneFx/2pQgu+XVf0DOXDH/KUgvX0KOSYoiq9E/TmxOzPZi9dDgJIe+zRzJFRx8sMYM+LXBJg1Q9jHL9qO1roqj0gNckI+YMgmy+STXJ25NF+1eMhUrX4N6SQ8JXoUhgFN1YLSptHuwSuVfGPwwrqPPpKDC1MT540dX/3+wdxqnri5VRGw0Y2ZdIKJ42IU7BnCuCEZPnqdM1W4osNbvv3UCQ5nqntd5v78KDQM1m3CxFugV35hbtbQExSMGUOvsk0WME=,iv:cgA+4zefeBWxqqep+hzgWl2ICKycss14GqFc+sCho24=,tag:THhTdS75Hu42enAsDq+3iA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTAreU5icVJCWWhET3VH
            MTY4aGJadTBxWEtPWEpnSXFmRFA5ZnVFNlFZCk5MaGhwZFdUaVBxc2xZcWZHYWs2
            M0dFN0hnOFVvVlNqbnZWcW1USStpbUEKLS0tIHNrTWQ0T3hBc0RCWWQwem94WXZY
            NmlwUGkrQ3c0SFUrenhxaUN6Z2VpMzgKrZcTcVoX5jIHRWsGJd7MrcxXxFZbahHE
            oAGUcSs6viLKEwYm4LdJN+gZR28L01wN7iigD+Tm5rJzBZvXkLkb3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjNrUlV2STFBSUVtUExZ
            VnlFcTRYYjJtbXowd011ME1BcEc0WGF3cld3CkZEbllQWVBRU0VYZ1JFRlNPcXFw
            S3YrMGdnZXVKSzA5VmFmdUtDaVRjMlkKLS0tIGQ2S216Yjh3RElCYUZCcU01cytZ
            Z1p2QXBySml2dzZ1cDFyOFNOdnBSaXcKIv82lUxlBHJ+cL7QeqmcANixp/QHfMXh
            gS0CZ5HhtagbgcjaNtogS5tGimNgJd+wqKvW/mNqve9FO2P4BCigGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T13:44:21Z"
    mac: ENC[AES256_GCM,data:ydEEA/k7XBWnc4b7pB7BaXmLobe4wonONKMCcHfs79jOsvtgcH3qRE5VB96yjGCy1G9+K7Knpr8QxuiSM2uYlHuxQpfnWF0nErj7h2XkFDloitoezNeCxWooTak1XgSrlSjz5hzNMoRumLt3kqddfC2aO7miweB6tBF+75z1urU=,iv:jeNNF0CfzuoV090Yx/un51oWwgW0pCNwrHjf4xNcnis=,tag:y5oHaAhCmcBvs0MCr8l1NA==,type:str]
    version: 3.13.0
