apiVersion: v1
kind: Secret
metadata:
    name: mas-oidc-config
    namespace: chats
stringData:
    config.yaml: ENC[AES256_GCM,data:DDZ/d+FF+LWbznWD2NHK0aI3s5VwOIzF3cvDqv27DJtnR0kexNUsUbVsBKugw/7s3yuL28m4PVJDOkpjSGyE9WQ0PlEXGpsWupJt5dy7sJdeQQVDV+Af3oKVdTsgjFDhJDa/VDZWpc627A5845zU7abwfo55fSM8ea1imY+H1alxcNb4Ev7NZRTiVov4sF9Sfk468rRFYeiwiQjBPhrPZn75lvJtq4P7BnfIuIQ5c19166lXG9Kyuilm6by+dR8gwC+6BVKVPnM+JPcGDnufac2FGs2sHFQb4v+bETOJkh4QB49h6qgzOfOtKFBbwIXD8tDUkeFzVIm5S/Z89JJ72LJ+3GHbizB8VuJE5fhM7+WLPSCWj1XxnfIUG/Na3TYEZkiLeMyCe7RdT8kgCIOQM5ug9lU09FZQFgUj/R9eicBI5hJN4Y3QX9DzuiZNMPttG4fYvDhhNefFu9XvATEG44psjTGtrqeKrhYqTe6aA59OX4Zv1YqPlE75gOtdNaA36EXFyQ7mj/ZZc5EqpQOsdtjBAZtI9Lv1dYrxshim33FcTnNb7S7wiEKys3gtTR4ccJXQX0TY1oydDUinXJt+30mvh+zen//vvLEj3QR2Hu+trzAyQ7JsbV1MD9RdJz7XykbJTGbjd8Ek8FxM3MI5VyXaCzRUOV4n0p+0aI9/OMnCFfkxvt+vZSn7Losrcpn1OeEq+zEDnhM7EaXkxeqRLX6QbWjuGWvauJC3NltbzksYC/Dzd9kliMXFaeDajFEXUXjtdyKmxnGxfZPwfu51lR1cO+ttd1HjUr0rbwmie9wrIl+rCQ/kRCrDE57eHXwpW/faFENzdNlj2E6WSIlk+v90PY67jt9Yye0m4u806eSML0q95cygS4yif9Q=,iv:UThn9r5Sjm+O3ewkAXI9UK7nPCaxfWSdvqXq1bgMK5Q=,tag:efsxwJBUrlovWixYLSsIBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYzgvSE5DMDl1TCtjdVVV
            SEQwSXlFRENxdHczYWZ6QURhWWRTSitFSEdFCnkvQXFFY1l0enFjMVdlU2JsaTkv
            NWl0Vm5UbStJUm1CcXFWOFFEL2xlYlUKLS0tIDREeXF6OHJyUFBwWG1mZG5iRXNT
            WjkxZGVLbnN2Q0c1UGJURzNQSkkzbUEKX0UdlQLxr4Sp4hDpIXW1JFCqGH1bNHPU
            4pIR2lPXqaVIjcrXa+54XJDryyHflJruqkRqzRCXK+txNZzuB2TNOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGsyMHQxVGZJclQ3T1NL
            cHRONUkxdGh3TVY2Z05TOWpMNi9kS211YUFzCnlMenhwbWM5citjVG81RWQzSjAw
            aE80YTFPc3ZURkZxcktLdTl5dzRKUE0KLS0tIGdqNzVMWmRQQlRQYTczUHlkV1RX
            bHFpNUwxR3VvZE41Z0xlaW5ZcFFmdG8KumvzI9S/bNNLzs2IiA3ilAiAxrwAJ6py
            5Qzmo9MsyZF15CvavqjQcz8Yo4LpsyH4hZBUhNHnfa65m+1d1x0ouA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T13:47:59Z"
    mac: ENC[AES256_GCM,data:YH3bKOqk97bm2KFqNiccPbM9hCsQgo1nvc+SV7wdcnvM3XD8rppnZwVyTmNRJ+n0Jp2MdA3M7T/NZVMJJyzheIJFgq7Wx1SVqgWgolG8do9/pjl9SqJ5w01yKYE8h3lopv/zIGi/8gg4vO12Vy/qz5aLmrxvD4P4GGcmvxXLywY=,iv:kozrvmXs8eqA2kNg4E8GCAYG9bfdBH22tt6BbQGOGDU=,tag:+jbo8KTcuJPkKMRywQVFKg==,type:str]
    version: 3.13.0
