apiVersion: batch/v1
kind: Job
metadata:
  name: wiredoor-register-synapse
  namespace: gateway
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: wiredoor-cli
        image: wiredoor/wiredoor-cli:v1.2.0
        command:
        - sh
        - -c
        - |
          wiredoor config --url=$WIREDOOR_URL --token=$WIREDOOR_TOKEN
          wiredoor http matrix \
            --domain matrix.titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 8088 --proto http
          wiredoor http maccount \
            --domain maccount.titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 8088 --proto http
          wiredoor http chat \
            --domain chat.titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 8088 --proto http
          wiredoor http madmin \
            --domain madmin.titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 8088 --proto http
          wiredoor http titusio \
            --domain titusio.net \
            --backendHost traefik.traefik.svc.cluster.local \
            --port 8088 --proto http
        env:
        - name: WIREDOOR_URL
          valueFrom:
            secretKeyRef:
              name: wiredoor-config
              key: WIREDOOR_URL
        - name: WIREDOOR_TOKEN
          valueFrom:
            secretKeyRef:
              name: wiredoor-config
              key: TOKEN
      restartPolicy: OnFailure
