apiVersion: v1
kind: Secret
metadata:
    name: synapse-db-credentials
    namespace: chats
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1MraEmEh2g==,iv:XKOuog5xl6FfyDJuYvBdWyh7SDV+NnEe5EeA+MZHLT0=,tag:2xp9LnXKIWGU0cCdmfhrYg==,type:str]
    password: ENC[AES256_GCM,data:WqMSNOFDmFljb9UgJbOw5RuSyfkooFi6pCkzE0FjfoL2E9oU/9waf2LNFn7MW99Nsc5ePdGJA/3rb4HU+W1xcA==,iv:BB88098Ay+Sax6Frg9ne53EZR5Tm0d2rVS4FzUxAjQg=,tag:tDeaz7lnpJOE6HTV9OgAsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObk5WMzJ0QnROM09zSEYz
            QWFaVUNiNllLVktMS0JUUjZoNVZ0bjdFYjFBCk1aR0k0UXUrRE5jSUdYVWdjREVO
            Y0h4bjA0TDlPa29kVlEyeDBvQU1UbVEKLS0tIGduaENUaUt4eElvWFVXY2ZyaUdl
            MXhJYllRVHhNYW1jWXNkWUZReklEV28KQAqJnUPzZa9qbnpwvVcLms48ace5OFG5
            ItscN5NcdkJpt7ijM/k5XRGXEDzFkXZvox2/JHfbwZgFRdZYLFY1PQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWnJWanpoOHE1VHJveld5
            VkozWnVNN2VVNER6RUpPditQN09OeFNzMHhjCmNQZGdjdysrVEZBTTcyVVZCb1Yv
            MnBsNFRXQUZRTmEzUXFiZEUzenR4TG8KLS0tIGNPYzYvSEZpaVJOVFBkcXF0UWgy
            cDE0OGNjR04zaVpMQWtTRVFCVmNBTU0KP/dCc2+ouNnmfcGPkB4uNALIXsXNdI0+
            qNECwm0QCx3ctTTxpF7dceEQTNwbpLlcK0qeosJYIVVkhE1b8jND8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T12:59:11Z"
    mac: ENC[AES256_GCM,data:1WBE5coSjPWorc8OYJkXdyPZHbzUCQQaBWgIM7FYVzA4RAS9D4a8EbxBnWODBik2pd35y/YCQqKsKCcBxqTUcIE4wgiRDoLQbsL0+Q/jjJ9aIQUD6cKhILPA5qwrQI+2srJX02BGFxF2pEyUThhTpJ0ROfhVrqrh1n2SsQ3Ae7Q=,iv:hvPf6N0c/cANwlbMOsXeu+zlq+8lQFRHcxE495vgMUo=,tag:PwXuti0W0vboV/95xcImvw==,type:str]
    version: 3.13.0
