apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: photos
spec:
  instances: 3
  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
  storage:
    size: 5Gi
  postgresql:
    parameters:
      shared_preload_libraries: "vectors.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vectors;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
