apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: photos
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fxh2EJ/S,iv:Uo2Z0lFE6QlvHxkMjUxHZgBiPH9VqSgFuTy5wsnVmq4=,tag:qyBhEP44MwiItwZSHVgZBg==,type:str]
    password: ENC[AES256_GCM,data:srxxdZe/2JRkZFujan87zC6QGHHOIfbBLnLzynHfdGE=,iv:br9yuuVSxx1EB+nvOdWbfEaMBLeaL++rWjkOCBCuejM=,tag:+66zYmwtmVxDQBHr378mSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZN01xMHVwQ1ZnN0Rvd0pu
            UmhKQkdBU0tsRFp4STRCdFQvMFFZd0lHTWxBCjBHeDkvZms2TXpjZ0gwc2JTRkhH
            MS9iZVZNM09ZN0dBam1lOHJnYTQxNVEKLS0tIFJRTnUzdUtnbFplb1dIZXAvOWZr
            QmJIRlRJclNuNnNTVldva0xxMnI4eWsK+3QoPJU3uU43Sp0B+7mWuqsKpKy+Lnba
            76xL/K1059WgZp9Jml1vbWIs5mZMpwOLxhxeVud5z/Zad543S5aSPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nudm99kz5ha33pz2e7h5qfe6zeth7mnh39luyjfr7kpzj32k392qpd4jff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbEo1S1B0L2lKVnJmSHIv
            cW9QTUc1czl5U1dKTThPYnF1dlpPNHBxYUVzCjVwbTZiUkRFYm9ZWnhKeEZad1Fs
            TURVVzB5QXRBeUJmOHc1Y1BQY3RzcTQKLS0tIHRjcTNXeDBxNFFIYlJjbWZHQ1l4
            SzFZcm9OQUxLdldQbUZnbUFpT0FGRTAKQOiTWzuzvmkPQDGGogg/O9q7flbtSPJY
            wwWDEsUU+uXJaYvXq/Inz12LZOfnbj6gQJ+UB3EYexWOJWOI7+TKmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywn62vszqd5n9g4v3rphmqc620t7u852xzctzk80afp4vu57n45qdqhlem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T16:42:02Z"
    mac: ENC[AES256_GCM,data:6U2xR/jgrSU5+mA+kHdZgFFzCj94YmW4rrUtVrVF0T1VBm9RElp++zKUNB9aUdMcf6XHU21f8tfu1twyYqdi3zNMua6YKvWzaOBN+EzHLCt5qXV1nFB3W9wPOTpFwyDx7SQdlCXPwXSRbIALzfbGl0u6Ft6GMfavJ7HNBIQVHKM=,iv:10AAmKjz9jVZ7fBRvUQTJLYPbEl1PRejo4yxHIELuZs=,tag:bpWhcvUeQXataUcT/db9ow==,type:str]
    version: 3.13.1
