name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # - name: Access private repository
      #   uses: webfactory/ssh-agent@master
      #   with:
      #     ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v18
      - id: update
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          commit-msg: "flake: update"
          pr-title: "flake: update"
          pr-labels: auto-merge
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge
        run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
